// frontend/src/lib/components/Confirm.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { t } from "svelte-i18n";

let {
    open = $bindable(false),
    title = "",
    yesText = "",
    noText = "",
    btnStyle = "btn-primary",
    onyes,
    onno,
    children,
} : {
    open?: boolean;
    title?: string;
    yesText?: string;
    noText?: string;
    btnStyle?: string;
    onyes?: () => void;
    onno?: () => void;
    children?: Snippet;
} = $props();

let dialogEl: HTMLDialogElement;

$effect(() => {
    if (!dialogEl) {
        return;
    }
    if (open) {
        dialogEl.showModal();
    } else {
        dialogEl.close();
    }
});

function yes() {
    open = false;
    onyes?.();
}

function no() {
    open = false;
    onno?.();
}
</script>

<dialog
    bind:this={dialogEl}
    onclose={() => (open = false)}
    onclick={(e) => {
        if (e.target === dialogEl) {
            no();
        }
    }}
>
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">{title || $t("Confirm")}</h5>
            <button class="btn-close" onclick={no} aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {#if children}{@render children()}{/if}
        </div>
        <div class="modal-footer">
            <button class="btn btn-secondary" onclick={no}>
                {noText || $t("No")}
            </button>
            <button class="btn {btnStyle}" onclick={yes}>
                {yesText || $t("Yes")}
            </button>
        </div>
    </div>
</dialog>

<style>
dialog { max-width: 500px; width: calc(100% - 2rem); }
</style>

// frontend/src/components/Confirm.vue
<template>
    <div ref="modal" class="modal fade" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 id="exampleModalLabel" class="modal-title">
                        {{ title || $t("Confirm") }}
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" />
                </div>
                <div class="modal-body">
                    <slot />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" :class="btnStyle" data-bs-dismiss="modal" @click="yes">
                        {{ yesText || $t('Yes') }}
                    </button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" @click="no">
                        {{ noText || $t('No') }}
                    </button>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import { Modal } from "bootstrap";

export default {
    props: {
        /** Style of button */
        btnStyle: {
            type: String,
            default: "btn-primary",
        },
        yesText: {
            type: String,
            default: "",
        },
        noText: {
            type: String,
            default: "",
        },
        /** Title to show on modal. Defaults to translated version of "Config" */
        title: {
            type: String,
            default: null,
        }
    },
    emits: [ "yes", "no" ],
    data: () => ({
        modal: null,
    }),
    mounted() {
        this.modal = new Modal(this.$refs.modal);
    },
    methods: {
        /**
         * Show the confirm dialog
         * @returns {void}
         */
        show() {
            this.modal.show();
        },
        /**
         * @fires string "yes" Notify the parent when Yes is pressed
         * @returns {void}
         */
        yes() {
            this.$emit("yes");
        },
        /**
         * @fires string "no" Notify the parent when No is pressed
         * @returns {void}
         */
        no() {
            this.$emit("no");
        }
    },
};
</script>
