// frontend/src/lib/components/ProgressTerminal.svelte
<script lang="ts">
import { t } from "svelte-i18n";
import Terminal from "./Terminal.svelte";
import Icon from "./Icon.svelte";
import { PROGRESS_TERMINAL_ROWS } from "../../../../common/util-common";

const {
    name,
    endpoint,
    rows = PROGRESS_TERMINAL_ROWS,
    autoHideTimeout = 10000,
} = $props<{
    name: string;
    endpoint: string;
    rows?: number;
    autoHideTimeout?: number;
}>();

interface TerminalInstance {
    clearTerminal: () => void;
    bind: (ep?: string, n?: string) => void;
    rebind: () => void;
    updateTerminalSize: () => void;
}

let showTerminal = $state(false);
let terminalRef = $state<TerminalInstance | undefined>(undefined);
let hideTimer: ReturnType<typeof setTimeout> | undefined;

export function show() {
    terminalRef?.bind(endpoint, name);
    terminalRef?.clearTerminal();
    showTerminal = true;
    clearTimeout(hideTimer);
}

export function hideWithTimeout() {
    if (autoHideTimeout > 0) {
        hideTimer = setTimeout(() => {
            showTerminal = false;
        }, autoHideTimeout);
    }
}
</script>

<div class="progress-terminal">
    <button
        type="button"
        class="terminal-header"
        onclick={() => (showTerminal = !showTerminal)}
    >
        <Icon name={showTerminal ? "chevron-down" : "chevron-right"} />
        {$t("terminal")}
    </button>

    {#if showTerminal}
        <div class="terminal-body">
            <Terminal
                bind:this={terminalRef}
                {name}
                {endpoint}
                {rows}
                mode="displayOnly"
            />
        </div>
    {/if}
</div>

<style>
.progress-terminal {
    background: var(--arbour-bg);
    box-shadow: 0 15px 70px rgba(0, 0, 0, 0.1);
    border-radius: var(--arbour-radius);
    overflow: hidden;
}

.terminal-header {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    width: 100%;
    padding: 0.6rem 1rem;
    background: var(--arbour-bg-header);
    border: none;
    color: var(--arbour-text);
    cursor: pointer;
    font-size: 0.9rem;
    font-family: inherit;
    text-align: left;
    transition: background 0.1s;
}

.terminal-header:hover {
    background: var(--arbour-bg-header-active);
}

.terminal-body {
    padding: 0.5rem;
    background: #000;
}
</style>

// frontend/src/components/ProgressTerminal.vue
<template>
    <div class="shadow-box">
        <div class="progress-terminal-header mb-1" @click="showProgressTerminal = !showProgressTerminal">
            <font-awesome-icon :icon="showProgressTerminal ? 'chevron-down' : 'chevron-right'" class="me-2" />
            {{ $t("terminal") }}
        </div>
        <transition name="slide-fade" appear>
            <Terminal
                v-show="showProgressTerminal"
                ref="progressTerminal"
                class="terminal"
                :name="name"
                :endpoint="endpoint"
                :rows="rows"
            ></Terminal>
        </transition>
    </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { PROGRESS_TERMINAL_ROWS } from "../../../common/util-common";
import Terminal from "./Terminal.vue";

let autoHideTerminalTimout: ReturnType<typeof setTimeout> | undefined = undefined;

export default defineComponent({
    components: {
        Terminal
    },

    props: {
        name: {
            type: String,
            required: true
        },
        endpoint: {
            type: String,
            required: true
        },
        rows: {
            type: Number,
            default: PROGRESS_TERMINAL_ROWS
        },
        autoHideTimeout: {
            type: Number,
            default: 10000
        }
    },

    data() {
        return {
            showProgressTerminal: false,
        };
    },

    computed: {
        progressTerminal(): typeof Terminal {
            return this.$refs.progressTerminal as typeof Terminal;
        }
    },

    mounted() {
    },

    methods: {
        show() {
            this.progressTerminal.bind(this.endpoint, this.name);
            this.progressTerminal.clearTerminal();
            this.showProgressTerminal = true;
            clearTimeout(autoHideTerminalTimout);
        },

        hideWithTimeout() {
            if (this.autoHideTimeout > 0) {
                autoHideTerminalTimout = setTimeout(async () => {
                    this.showProgressTerminal = false;
                }, this.autoHideTimeout);
            }
        },
    }
});
</script>

<style lang="scss" scoped>
    @import "../styles/vars.scss";

    .progress-terminal-header {
        cursor: pointer;
    }

</style>
