// frontend/src/lib/components/StackListItem.svelte
<script lang="ts">
import { page } from "$app/stores";
import Uptime from "./Uptime.svelte";
import Icon from "./Icon.svelte";
import { socketStore } from "$lib/stores/socket.svelte";
import type { SimpleStackData } from "../../../../common/types";

const { stack } = $props<{ stack: SimpleStackData }>();

const url = $derived(
    stack.endpoint
        ? `/compose/${stack.name}/${stack.endpoint}`
        : `/compose/${stack.name}`
);

const isActive = $derived($page.url.pathname === url);
const agentCount = $derived(socketStore.agentCount);
const endpointDisplay = $derived(socketStore.getAgentName(stack.endpoint ?? ""));
</script>

<a href={url} class="item" class:active={isActive} class:dim={!stack.isManagedByArbour}>
    <Uptime {stack} fixedWidth={true} />
    <div class="title">
        <span class="name">{stack.name}</span>
        {#if stack.started && stack.recreateNecessary}
            <Icon name="rocket" class="notification-icon" />
        {/if}
        {#if stack.started && stack.imageUpdatesAvailable}
            <Icon name="arrow-up" class="notification-icon" />
        {/if}
        {#if agentCount > 1}
            <div class="endpoint">{endpointDisplay}</div>
        {/if}
    </div>
</a>

<style>
.item {
    text-decoration: none;
    display: flex;
    align-items: center;
    gap: 0.5rem;
    min-height: 52px;
    border-radius: 10px;
    transition: all ease-in-out 0.15s;
    width: 100%;
    padding: 5px 8px;
    color: var(--arbour-text);
}

.item:hover,
.item.active {
    background-color: var(--arbour-bg-deep);
}

.item.dim {
    opacity: 0.5;
}

.title {
    display: flex;
    align-items: center;
    gap: 0.35rem;
    margin-top: -4px;
    flex-wrap: wrap;
}

.name {
    font-weight: 500;
}

.endpoint {
    font-size: 12px;
    color: var(--arbour-text-muted);
}

:global(.notification-icon) {
    color: var(--arbour-info);
}
</style>

// frontend/src/components/StackListItem.vue
<template>
    <router-link :to="url" :class="{ 'dim' : !stack.isManagedByArbour }" class="item">
        <Uptime :stack="stack" :fixed-width="true" class="me-2" />
        <div class="title">
            <span class="me-2">{{ stack.name }}</span>
            <font-awesome-icon v-if="stack.started && stack.recreateNecessary" icon="rocket" class="notification-icon me-2" />
            <font-awesome-icon v-if="stack.started && stack.imageUpdatesAvailable" icon="arrow-up" class="notification-icon me-2" />
            <div v-if="agentCount > 1" class="endpoint">{{ endpointDisplay }}</div>
        </div>
    </router-link>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import Uptime from "./Uptime.vue";
import { SimpleStackData } from "../../../common/types";

export default defineComponent({
    components: {
        Uptime
    },
    props: {
        /** Stack this represents */
        stack: {
            type: Object as PropType<SimpleStackData>,
            default: null,
        },
        /** If the user is in select mode */
        isSelectMode: {
            type: Boolean,
            default: false,
        },
        /** How many ancestors are above this stack */
        depth: {
            type: Number,
            default: 0,
        },
        /** Callback to determine if stack is selected */
        isSelected: {
            type: Function,
            default: () => {}
        },
        /** Callback fired when stack is selected */
        select: {
            type: Function,
            default: () => {}
        },
        /** Callback fired when stack is deselected */
        deselect: {
            type: Function,
            default: () => {}
        },
    },
    data() {
        return {
            isCollapsed: true,
        };
    },
    computed: {
        endpointDisplay() {
            return this.$root.getAgentName(this.stack.endpoint);
        },
        agentCount() {
            return this.$root.agentCount;
        },
        url() {
            if (this.stack.endpoint) {
                return `/compose/${this.stack.name}/${this.stack.endpoint}`;
            } else {
                return `/compose/${this.stack.name}`;
            }
        },
        depthMargin() {
            return {
                marginLeft: `${31 * this.depth}px`,
            };
        },
    },
    watch: {
        isSelectMode() {
            // TODO: Resize the heartbeat bar, but too slow
            // this.$refs.heartbeatBar.resize();
        }
    },
    beforeMount() {

    },
    methods: {
        /**
         * Changes the collapsed value of the current stack and saves
         * it to local storage
         * @returns {void}
         */
        changeCollapsed() {
            this.isCollapsed = !this.isCollapsed;

            // Save collapsed value into local storage
            let storage = window.localStorage.getItem("stackCollapsed");
            let storageObject = {};
            if (storage !== null) {
                storageObject = JSON.parse(storage);
            }
            storageObject[`stack_${this.stack.id}`] = this.isCollapsed;

            window.localStorage.setItem("stackCollapsed", JSON.stringify(storageObject));
        },

        /**
         * Toggle selection of stack
         * @returns {void}
        toggleSelection() {
            if (this.isSelected(this.stack.id)) {
                this.deselect(this.stack.id);
            } else {
                this.select(this.stack.id);
            }
        },*/
    },
});
</script>

<style lang="scss" scoped>
@import "../styles/vars.scss";

.small-padding {
    padding-left: 5px !important;
    padding-right: 5px !important;
}

.collapse-padding {
    padding-left: 8px !important;
    padding-right: 2px !important;
}

.item {
    text-decoration: none;
    display: flex;
    align-items: center;
    min-height: 52px;
    border-radius: 10px;
    transition: all ease-in-out 0.15s;
    width: 100%;
    padding: 5px 8px;
    &.disabled {
        opacity: 0.3;
    }
    &:hover {
        background-color: var(--arbour-bg-deep);
    }
    &.active {
        background-color: var(--arbour-bg-deep);
    }
    .title {
        margin-top: -4px;
    }
    .endpoint {
        font-size: 12px;
        color: var(--arbour-text-muted);
    }
}

.collapsed {
    transform: rotate(-90deg);
}

.animated {
    transition: all 0.2s $easing-in;
}

.select-input-wrapper {
    float: left;
    margin-top: 15px;
    margin-left: 3px;
    margin-right: 10px;
    padding-left: 4px;
    position: relative;
    z-index: 15;
}

.dim {
    opacity: 0.5;
}

.notification-icon {
    color: var(--arbour-info);
    font-weight: bold;
}

</style>
