// frontend/src/lib/components/TwoFADialog.svelte
<script lang="ts">
import { onMount } from "svelte";
import { t } from "svelte-i18n";
import { socketStore } from "$lib/stores/socket.svelte";
import Confirm from "./Confirm.svelte";
import type { SocketRes } from "$lib/types";
import QRCode from "qrcode";

let { open = $bindable(false) } : { open?: boolean } = $props();

let currentPassword = $state("");
let processing = $state(false);
let uri = $state<string | null>(null);
let tokenValid = $state(false);
let twoFAStatus = $state<boolean | null>(null);
let token = $state("");
let showURI = $state(false);
let qrDataUrl = $state("");
let dialogEl: HTMLDialogElement;

let confirmEnableOpen = $state(false);
let confirmDisableOpen = $state(false);

$effect(() => {
    if (!dialogEl) {
        return;
    }
    if (open) {
        dialogEl.showModal();
    } else {
        dialogEl.close();
    }
});

$effect(() => {
    if (uri) {
        QRCode.toDataURL(uri, { color: { light: "#ffffffff" },
            width: 210 }).then((url) => {
            qrDataUrl = url;
        });
    }
});

onMount(() => {
    getStatus();
});

function close() {
    open = false;
}

function getStatus() {
    socketStore.getSocket().emit("twoFAStatus", (res: SocketRes) => {
        if (res.ok) {
            twoFAStatus = res.status as boolean | null;
        } else {
            socketStore.toastRes(res);
        }
    });
}

function prepare2FA() {
    processing = true;
    socketStore.getSocket().emit("prepare2FA", currentPassword, (res: SocketRes) => {
        processing = false;
        if (res.ok) {
            uri = res.uri as string | null;
        } else {
            socketStore.toastRes(res);
        }
    });
}

function verifyToken() {
    socketStore.getSocket().emit("verifyToken", token, currentPassword, (res: SocketRes) => {
        if (res.ok) {
            tokenValid = res.valid as boolean;
        } else {
            socketStore.toastRes(res);
        }
    });
}

function save2FA() {
    processing = true;
    socketStore.getSocket().emit("save2FA", currentPassword, (res: SocketRes) => {
        processing = false;
        if (res.ok) {
            socketStore.toastRes(res);
            getStatus();
            currentPassword = "";
            close();
        } else {
            socketStore.toastRes(res);
        }
    });
}

function disable2FA() {
    processing = true;
    socketStore.getSocket().emit("disable2FA", currentPassword, (res: SocketRes) => {
        processing = false;
        if (res.ok) {
            socketStore.toastRes(res);
            getStatus();
            currentPassword = "";
            close();
        } else {
            socketStore.toastRes(res);
        }
    });
}
</script>

<dialog
    bind:this={dialogEl}
    onclose={() => (open = false)}
    onclick={(e) => {
        if (e.target === dialogEl) {
            close();
        }
    }}
>
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">
                {$t("Setup 2FA")}
                {#if twoFAStatus === true}
                    <span class="badge bg-primary ms-2">{$t("Active")}</span>
                {:else if twoFAStatus === false}
                    <span class="badge bg-secondary ms-2">{$t("Inactive")}</span>
                {/if}
            </h5>
            <button class="btn-close" onclick={close} disabled={processing} aria-label="Close"></button>
        </div>

        <div class="modal-body">
            {#if uri && twoFAStatus === false}
                <div class="qr-wrap text-center">
                    {#if qrDataUrl}
                        <img src={qrDataUrl} alt="QR Code" width="210" height="210" />
                    {/if}
                    {#if !showURI}
                        <div>
                            <button type="button" class="btn btn-sm btn-outline-primary mt-2" onclick={() => (showURI = true)}>
                                {$t("Show URI")}
                            </button>
                        </div>
                    {/if}
                </div>
                {#if showURI}
                    <p class="text-break mt-2">{uri}</p>
                {/if}

                <div class="mt-3">
                    <label for="twofa-token" class="form-label">{$t("twoFAVerifyLabel")}</label>
                    <div class="input-group">
                        <input
                            id="twofa-token"
                            class="form-control"
                            bind:value={token}
                            type="text"
                            maxlength="6"
                            autocomplete="one-time-code"
                        />
                        <button type="button" class="btn btn-outline-primary" onclick={verifyToken}>
                            {$t("Verify Token")}
                        </button>
                    </div>
                    {#if tokenValid}
                        <p class="text-primary mt-2 mb-0">{$t("tokenValidSettingsMsg")}</p>
                    {/if}
                </div>
            {:else}
                <div>
                    <label for="twofa-pass" class="form-label">{$t("Current Password")}</label>
                    <input
                        id="twofa-pass"
                        class="form-control"
                        bind:value={currentPassword}
                        type="password"
                        autocomplete="current-password"
                    />
                </div>

                {#if twoFAStatus === false}
                    <button type="button" class="btn btn-primary mt-3" onclick={prepare2FA}>
                        {$t("Enable 2FA")}
                    </button>
                {/if}

                {#if twoFAStatus === true}
                    <button
                        type="button"
                        class="btn btn-danger mt-3"
                        disabled={processing}
                        onclick={() => (confirmDisableOpen = true)}
                    >
                        {$t("Disable 2FA")}
                    </button>
                {/if}
            {/if}
        </div>

        {#if uri && twoFAStatus === false}
            <div class="modal-footer">
                <button
                    type="button"
                    class="btn btn-primary"
                    disabled={processing || !tokenValid}
                    onclick={() => (confirmEnableOpen = true)}
                >
                    {$t("Save")}
                </button>
            </div>
        {/if}
    </div>
</dialog>

<Confirm
    bind:open={confirmEnableOpen}
    btnStyle="btn-danger"
    yesText={$t("Yes")}
    noText={$t("No")}
    onyes={save2FA}
>
    {$t("confirmEnableTwoFAMsg")}
</Confirm>

<Confirm
    bind:open={confirmDisableOpen}
    btnStyle="btn-danger"
    yesText={$t("Yes")}
    noText={$t("No")}
    onyes={disable2FA}
>
    {$t("confirmDisableTwoFAMsg")}
</Confirm>

<style>
dialog { max-width: 480px; width: calc(100% - 2rem); }
.modal-title { display: flex; align-items: center; }
</style>

// frontend/src/components/TwoFADialog.vue
<template>
    <form @submit.prevent="submit">
        <div ref="modal" class="modal fade" tabindex="-1" data-bs-backdrop="static">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">
                            {{ $t("Setup 2FA") }}
                            <span v-if="twoFAStatus == true" class="badge bg-primary">{{ $t("Active") }}</span>
                            <span v-if="twoFAStatus == false" class="badge bg-primary">{{ $t("Inactive") }}</span>
                        </h5>
                        <button :disabled="processing" type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" />
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <div v-if="uri && twoFAStatus == false" class="mx-auto text-center" style="width: 210px;">
                                <vue-qrcode :key="uri" :value="uri" type="image/png" :quality="1" :color="{ light: '#ffffffff' }" />
                                <button v-show="!showURI" type="button" class="btn btn-outline-primary btn-sm mt-2" @click="showURI = true">{{ $t("Show URI") }}</button>
                            </div>
                            <p v-if="showURI && twoFAStatus == false" class="text-break mt-2">{{ uri }}</p>

                            <div v-if="!(uri && twoFAStatus == false)" class="mb-3">
                                <label for="current-password" class="form-label">
                                    {{ $t("Current Password") }}
                                </label>
                                <input
                                    id="current-password"
                                    v-model="currentPassword"
                                    type="password"
                                    class="form-control"
                                    autocomplete="current-password"
                                    required
                                />
                            </div>

                            <button v-if="uri == null && twoFAStatus == false" class="btn btn-primary" type="button" @click="prepare2FA()">
                                {{ $t("Enable 2FA") }}
                            </button>

                            <button v-if="twoFAStatus == true" class="btn btn-danger" type="button" :disabled="processing" @click="confirmDisableTwoFA()">
                                {{ $t("Disable 2FA") }}
                            </button>

                            <div v-if="uri && twoFAStatus == false" class="mt-3">
                                <label for="basic-url" class="form-label">{{ $t("twoFAVerifyLabel") }}</label>
                                <div class="input-group">
                                    <input v-model="token" type="text" maxlength="6" class="form-control" autocomplete="one-time-code" required>
                                    <button class="btn btn-outline-primary" type="button" @click="verifyToken()">{{ $t("Verify Token") }}</button>
                                </div>
                                <p v-show="tokenValid" class="mt-2" style="color: green;">{{ $t("tokenValidSettingsMsg") }}</p>
                            </div>
                        </div>
                    </div>

                    <div v-if="uri && twoFAStatus == false" class="modal-footer">
                        <button type="submit" class="btn btn-primary" :disabled="processing || tokenValid == false" @click="confirmEnableTwoFA()">
                            <div v-if="processing" class="spinner-border spinner-border-sm me-1"></div>
                            {{ $t("Save") }}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <Confirm ref="confirmEnableTwoFA" btn-style="btn-danger" :yes-text="$t('Yes')" :no-text="$t('No')" @yes="save2FA">
        {{ $t("confirmEnableTwoFAMsg") }}
    </Confirm>

    <Confirm ref="confirmDisableTwoFA" btn-style="btn-danger" :yes-text="$t('Yes')" :no-text="$t('No')" @yes="disable2FA">
        {{ $t("confirmDisableTwoFAMsg") }}
    </Confirm>
</template>

<script lang="ts">
import { Modal } from "bootstrap";
import Confirm from "./Confirm.vue";
import VueQrcode from "vue-qrcode";
import { useToast } from "vue-toastification";
const toast = useToast();

export default {
    components: {
        Confirm,
        VueQrcode,
    },
    props: {},
    data() {
        return {
            currentPassword: "",
            processing: false,
            uri: null,
            tokenValid: false,
            twoFAStatus: null,
            token: null,
            showURI: false,
        };
    },
    mounted() {
        this.modal = new Modal(this.$refs.modal);
        this.getStatus();
    },
    methods: {
        /** Show the dialog */
        show() {
            this.modal.show();
        },

        /** Show dialog to confirm enabling 2FA */
        confirmEnableTwoFA() {
            this.$refs.confirmEnableTwoFA.show();
        },

        /** Show dialog to confirm disabling 2FA */
        confirmDisableTwoFA() {
            this.$refs.confirmDisableTwoFA.show();
        },

        /** Prepare 2FA configuration */
        prepare2FA() {
            this.processing = true;

            this.$root.getSocket().emit("prepare2FA", this.currentPassword, (res) => {
                this.processing = false;

                if (res.ok) {
                    this.uri = res.uri;
                } else {
                    toast.error(res.msg);
                }
            });
        },

        /** Save the current 2FA configuration */
        save2FA() {
            this.processing = true;

            this.$root.getSocket().emit("save2FA", this.currentPassword, (res) => {
                this.processing = false;

                if (res.ok) {
                    this.$root.toastRes(res);
                    this.getStatus();
                    this.currentPassword = "";
                    this.modal.hide();
                } else {
                    toast.error(res.msg);
                }
            });
        },

        /** Disable 2FA for this user */
        disable2FA() {
            this.processing = true;

            this.$root.getSocket().emit("disable2FA", this.currentPassword, (res) => {
                this.processing = false;

                if (res.ok) {
                    this.$root.toastRes(res);
                    this.getStatus();
                    this.currentPassword = "";
                    this.modal.hide();
                } else {
                    toast.error(res.msg);
                }
            });
        },

        /** Verify the token generated by the user */
        verifyToken() {
            this.$root.getSocket().emit("verifyToken", this.token, this.currentPassword, (res) => {
                if (res.ok) {
                    this.tokenValid = res.valid;
                } else {
                    toast.error(res.msg);
                }
            });
        },

        /** Get current status of 2FA */
        getStatus() {
            this.$root.getSocket().emit("twoFAStatus", (res) => {
                if (res.ok) {
                    this.twoFAStatus = res.status;
                } else {
                    toast.error(res.msg);
                }
            });
        },
    },
};
</script>

<style scoped>
.modal-dialog .form-text,
.modal-dialog p {
    color: var(--arbour-text);
}
</style>
