// frontend/src/components/ArraySelect.vue
<template>
    <div>
        <div v-if="composeArray.isValid() && !composeArray.containsObjects()">
            <ul class="list-group">
                <li v-for="(value, index) in array" :key="index" class="list-group-item">
                    <select v-model="array[index]" class="no-bg domain-input">
                        <option value="">{{ $t(`Select a network...`) }}</option>
                        <option v-for="option in options" :key="String(option)" :value="option">{{ option }}</option>
                    </select>

                    <font-awesome-icon icon="times" class="action remove ms-2 me-3 text-danger" @click="composeArray.delete(index)" />
                </li>
            </ul>

            <button class="btn btn-normal btn-sm mt-3" @click="composeArray.add('')">{{ $t("addListItem", [ displayName ]) }}</button>
        </div>
        <div v-else>
            Long syntax is not supported here. Please use the YAML editor.
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import { ComposeArray } from "../../../common/compose-document";

export default defineComponent({
    props: {
        composeArray: {
            type: Object as PropType<ComposeArray>,
            required: true,
        },
        placeholder: {
            type: String,
            default: "",
        },
        displayName: {
            type: String,
            required: true,
        },
        options: {
            type: Array,
            required: true,
        },
    },
    data() {
        return {};
    },
    computed: {
        array() {
            return this.composeArray.composeData.data;
        }
    },
    created() {

    },
    methods: {

    }
});
</script>

<style lang="scss" scoped>
@import "../styles/vars.scss";

.list-group {
    background-color: var(--arbour-bg-deep);

    li {
        display: flex;
        align-items: center;
        padding: 10px 0 10px 10px;

        .domain-input {
            flex-grow: 1;
            background-color: var(--arbour-bg-deep);
            border: none;
            color: var(--arbour-text);
            outline: none;
        }
    }
}
</style>

// frontend/src/lib/components/ArraySelect.svelte
<script lang="ts">
import { t } from "svelte-i18n";
import Icon from "./Icon.svelte";
import type { ComposeArray } from "../../../../common/compose-document";

const { composeArray, displayName, options } = $props<{
    composeArray: ComposeArray;
    displayName: string;
    options: string[];
}>();

const array = $derived(composeArray.composeData.data as string[]);
</script>

<div>
    {#if composeArray.isValid() && !composeArray.containsObjects()}
        <ul class="list-group">
            {#each array as value, index (index)}
                <li class="list-group-item">
                    <select bind:value={array[index]} class="domain-input">
                        <option value="">{$t("Select a network...")}</option>
                        {#each options as opt (opt)}
                            <option value={opt}>{opt}</option>
                        {/each}
                    </select>
                    <button type="button" class="remove-btn" onclick={() => composeArray.delete(index)}>
                        <Icon name="times" class="text-danger" />
                    </button>
                </li>
            {/each}
        </ul>
        <button class="btn btn-sm mt-3" type="button" onclick={() => composeArray.add("")}>
            {$t("addListItem", { values: { 0: displayName } })}
        </button>
    {:else}
        <span>{$t("LongSyntaxNotSupported")}</span>
    {/if}
</div>

<style>
.list-group {
    list-style: none;
    margin: 0;
    padding: 0;
    background-color: var(--arbour-bg-deep);
    border-radius: var(--arbour-radius);
    overflow: hidden;
}

.list-group-item {
    display: flex;
    align-items: center;
    padding: 10px 0 10px 10px;
    border-bottom: 1px solid var(--arbour-border);
}

.list-group-item:last-child {
    border-bottom: none;
}

.domain-input {
    flex-grow: 1;
    background-color: var(--arbour-bg-deep);
    border: none;
    color: var(--arbour-text);
    outline: none;
    font-size: inherit;
}

.remove-btn {
    background: none;
    border: none;
    cursor: pointer;
    padding: 0 0.75rem;
    line-height: 1;
}

.mt-3 { margin-top: 1rem; }
</style>
