// frontend/src/components/CodeEditor.vue
<template>
    <div class="code-editor" :class="{ 'code-editor-readonly': readonly }">
        <Codemirror
            :model-value="modelValue"
            :extensions="extensions"
            :disabled="readonly"
            @update:model-value="$emit('update:modelValue', $event)"
            @focus="$emit('focus')"
            @blur="$emit('blur')"
        />
    </div>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { Codemirror } from "vue-codemirror";
import { yaml } from "@codemirror/lang-yaml";
import { json } from "@codemirror/lang-json";
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags } from "@lezer/highlight";
import { EditorView } from "codemirror";

const props = defineProps<{
    modelValue: string;
    lang?: "yaml" | "json" | "env";
    readonly?: boolean;
}>();

defineEmits<{
    "update:modelValue": [value: string];
    "focus": [];
    "blur": [];
}>();

// Syntax token colors — CSS vars resolve at render time, so theme switches work automatically
const arbourHighlight = HighlightStyle.define([
    { tag: tags.keyword,       color: "var(--arbour-primary)" },
    { tag: tags.bool,          color: "var(--arbour-primary)" },
    { tag: tags.tagName,       color: "var(--arbour-primary)" },
    { tag: tags.string,        color: "var(--arbour-warning)" },
    { tag: tags.number,        color: "var(--arbour-danger)" },
    { tag: tags.propertyName,  color: "var(--arbour-info)" },
    { tag: tags.attributeName, color: "var(--arbour-info)" },
    { tag: tags.labelName,     color: "var(--arbour-info)" },
    { tag: tags.typeName,      color: "var(--arbour-maintenance)" },
    { tag: tags.variableName,  color: "var(--arbour-text)" },
    { tag: tags.null,          color: "var(--arbour-text-muted)" },
    { tag: tags.comment,       color: "var(--arbour-text-muted)", fontStyle: "italic" },
    { tag: tags.meta,          color: "var(--arbour-text-muted)" },
    { tag: tags.operator,      color: "var(--arbour-text-subtle)" },
    { tag: tags.punctuation,   color: "var(--arbour-text-subtle)" },
    { tag: tags.link,          color: "var(--arbour-info)", textDecoration: "underline" },
]);

// Editor chrome for edit mode — themed background, gutter, cursor, selection
const arbourEditorTheme = EditorView.theme({
    "&": {
        backgroundColor: "var(--arbour-bg-deep)",
        color: "var(--arbour-text)",
    },
    ".cm-content": {
        caretColor: "var(--arbour-primary)",
    },
    ".cm-cursor, .cm-dropCursor": {
        borderLeftColor: "var(--arbour-primary)",
    },
    ".cm-gutters": {
        backgroundColor: "var(--arbour-bg)",
        color: "var(--arbour-text-muted)",
        borderRight: "1px solid var(--arbour-border)",
    },
    ".cm-lineNumbers .cm-gutterElement": {
        color: "var(--arbour-text-muted)",
    },
    ".cm-activeLineGutter": {
        backgroundColor: "var(--arbour-bg-header)",
    },
    ".cm-activeLine": {
        backgroundColor: "color-mix(in srgb, var(--arbour-primary) 5%, transparent)",
    },
    "&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection": {
        backgroundColor: "color-mix(in srgb, var(--arbour-primary) 20%, transparent)",
    },
    ".cm-matchingBracket": {
        color: "var(--arbour-primary) !important",
        backgroundColor: "color-mix(in srgb, var(--arbour-primary) 15%, transparent)",
    },
    ".cm-tooltip": {
        backgroundColor: "var(--arbour-bg)",
        border: "1px solid var(--arbour-border)",
        color: "var(--arbour-text)",
    },
    ".cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]": {
        backgroundColor: "var(--arbour-bg-header-active)",
    },
});

// Base layout — font, height, transparent bg (used in both modes)
const baseTheme = EditorView.theme({
    "&": {
        height: "100%",
    },
    ".cm-content": {
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: "14px",
    },
    ".cm-gutterElement": {
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: "14px",
    },
});

const extensions = computed(() => {
    const ext = [ baseTheme, EditorView.lineWrapping ];

    if (!props.readonly) {
        ext.push(arbourEditorTheme);
    }

    ext.push(syntaxHighlighting(arbourHighlight));

    if (props.lang === "yaml" || props.lang === "env") {
        ext.push(yaml());
    } else if (props.lang === "json") {
        ext.push(json());
    }

    if (props.readonly) {
        ext.push(EditorView.editable.of(false));
    }

    return ext;
});
</script>

<style lang="scss" scoped>
@import "../styles/vars.scss";

.code-editor {
    height: 100%;
    overflow: auto;
    border-radius: 5px;
}

:deep(.cm-editor) {
    height: 100%;
    border-radius: 5px;

    .cm-scroller {
        border-radius: 5px;
    }
}

.code-editor-readonly {
    :deep(.cm-editor) {
        background-color: transparent;
        color: var(--arbour-text);

        .cm-gutters {
            display: none;
        }

        .cm-activeLine {
            background-color: transparent;
        }

        .cm-cursor {
            display: none;
        }
    }
}
</style>

// frontend/src/lib/components/CodeEditor.svelte
<script lang="ts">
import { onMount, onDestroy } from "svelte";
import { EditorView } from "@codemirror/view";
import { EditorState, Compartment } from "@codemirror/state";
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags } from "@lezer/highlight";
import { yaml } from "@codemirror/lang-yaml";
import { json } from "@codemirror/lang-json";

let {
    value = $bindable(""),
    lang = "yaml" as "yaml" | "json" | "env",
    readonly = false,
    onfocus = undefined,
    onblur = undefined,
} = $props<{
    value?: string;
    lang?: "yaml" | "json" | "env";
    readonly?: boolean;
    onfocus?: () => void;
    onblur?: () => void;
}>();

let editorEl: HTMLDivElement;
let view: EditorView;
let lastEditorValue = "";

const langComp = new Compartment();
const editableComp = new Compartment();

const arbourHighlight = HighlightStyle.define([
    { tag: tags.keyword, color: "var(--arbour-primary)" },
    { tag: tags.bool, color: "var(--arbour-primary)" },
    { tag: tags.tagName, color: "var(--arbour-primary)" },
    { tag: tags.string, color: "var(--arbour-warning)" },
    { tag: tags.number, color: "var(--arbour-danger)" },
    { tag: tags.propertyName, color: "var(--arbour-info)" },
    { tag: tags.attributeName, color: "var(--arbour-info)" },
    { tag: tags.labelName, color: "var(--arbour-info)" },
    { tag: tags.typeName, color: "var(--arbour-maintenance)" },
    { tag: tags.variableName, color: "var(--arbour-text)" },
    { tag: tags.null, color: "var(--arbour-text-muted)" },
    { tag: tags.comment, color: "var(--arbour-text-muted)", fontStyle: "italic" },
    { tag: tags.meta, color: "var(--arbour-text-muted)" },
    { tag: tags.operator, color: "var(--arbour-text-subtle)" },
    { tag: tags.punctuation, color: "var(--arbour-text-subtle)" },
    { tag: tags.link, color: "var(--arbour-info)", textDecoration: "underline" },
]);

const baseTheme = EditorView.theme({
    "&": { height: "100%" },
    ".cm-content": { fontFamily: "'JetBrains Mono', monospace", fontSize: "14px" },
    ".cm-gutterElement": { fontFamily: "'JetBrains Mono', monospace", fontSize: "14px" },
});

const selectionTheme = EditorView.theme({
    "&.cm-focused .cm-selectionBackground, .cm-selectionBackground": {
        backgroundColor: "var(--arbour-selection-bg)",
    },
    ".cm-content ::selection": {
        backgroundColor: "var(--arbour-selection-bg)",
        color: "var(--arbour-selection-color)",
    },
});

const editorTheme = EditorView.theme({
    "&": { backgroundColor: "var(--arbour-bg-deep)", color: "var(--arbour-text)" },
    ".cm-content": { caretColor: "var(--arbour-primary)" },
    ".cm-cursor, .cm-dropCursor": { borderLeftColor: "var(--arbour-primary)" },
    ".cm-gutters": {
        backgroundColor: "var(--arbour-bg)",
        color: "var(--arbour-text-muted)",
        borderRight: "1px solid var(--arbour-border)",
    },
    ".cm-lineNumbers .cm-gutterElement": { color: "var(--arbour-text-muted)" },
    ".cm-activeLineGutter": { backgroundColor: "var(--arbour-bg-header)" },
    ".cm-activeLine": { backgroundColor: "color-mix(in srgb, var(--arbour-primary) 5%, transparent)" },
    ".cm-matchingBracket": {
        color: "var(--arbour-primary) !important",
        backgroundColor: "color-mix(in srgb, var(--arbour-primary) 15%, transparent)",
    },
    ".cm-tooltip": {
        backgroundColor: "var(--arbour-bg)",
        border: "1px solid var(--arbour-border)",
        color: "var(--arbour-text)",
    },
    ".cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]": {
        backgroundColor: "var(--arbour-bg-header-active)",
    },
});

function getLangExtension(l: string) {
    if (l === "yaml" || l === "env") return yaml();
    if (l === "json") return json();
    return [];
}

$effect(() => {
    if (!view) return;
    const l = lang;
    view.dispatch({ effects: langComp.reconfigure(getLangExtension(l)) });
});

$effect(() => {
    if (!view) return;
    const ro = readonly;
    view.dispatch({ effects: editableComp.reconfigure(EditorView.editable.of(!ro)) });
});

$effect(() => {
    if (!view) return;
    if (value === lastEditorValue) return;
    const current = view.state.doc.toString();
    if (current !== value) {
        view.dispatch({ changes: { from: 0, to: current.length, insert: value } });
    }
    lastEditorValue = value;
});

onMount(() => {
    view = new EditorView({
        state: EditorState.create({
            doc: value,
            extensions: [
                baseTheme,
                selectionTheme,
                editorTheme,
                EditorView.lineWrapping,
                syntaxHighlighting(arbourHighlight),
                langComp.of(getLangExtension(lang)),
                editableComp.of(EditorView.editable.of(!readonly)),
                EditorView.updateListener.of((update) => {
                    if (update.docChanged) {
                        lastEditorValue = update.state.doc.toString();
                        value = lastEditorValue;
                    }
                    if (update.focusChanged) {
                        if (update.view.hasFocus) onfocus?.();
                        else onblur?.();
                    }
                }),
            ],
        }),
        parent: editorEl,
    });
    lastEditorValue = value;
});

onDestroy(() => view?.destroy());
</script>

<div
    class="code-editor"
    class:code-editor-readonly={readonly}
    bind:this={editorEl}
></div>

<style>
.code-editor {
    height: 100%;
    overflow: auto;
    border-radius: var(--arbour-radius);
}

:global(.code-editor .cm-editor) {
    height: 100%;
    border-radius: var(--arbour-radius);
}

:global(.code-editor .cm-editor .cm-scroller) {
    border-radius: var(--arbour-radius);
}

.code-editor-readonly :global(.cm-editor) {
    background-color: transparent;
    color: var(--arbour-text);
}

.code-editor-readonly :global(.cm-gutters) {
    display: none;
}

.code-editor-readonly :global(.cm-activeLine) {
    background-color: transparent;
}

.code-editor-readonly :global(.cm-cursor) {
    display: none;
}
</style>
