// frontend/src/components/Container.vue
<template>
    <div class="shadow-box big-padding mb-3 container">
        <div class="service-header">
            <h4 class="service-title">{{ name }}</h4>
            <div class="service-actions">
                <button
                    v-if="!isEditMode && service.recreateNecessary"
                    class="btn btn-sm btn-info me-2"
                    data-toggle="tooltip" :title="$t('tooltipServiceRecreate')"
                    :disabled="processing"
                    @click="recreateService"
                >
                    <font-awesome-icon icon="rocket" />
                </button>

                <button
                    v-if="!isEditMode && service.imageUpdateAvailable"
                    v-b-modal="updateModalId"
                    data-toggle="tooltip" :title="$t('tooltipServiceUpdate')"
                    class="btn btn-sm btn-info me-2"
                    :disabled="processing"
                >
                    <font-awesome-icon icon="arrow-up" />
                </button>

                <!-- Image update modal -->
                <BModal :id="updateModalId" :ref="updateModalId" :title="$t('imageUpdate', 1)">
                    <div>
                        <h5>{{ $t("image") }}</h5>
                        <span>{{ composeService.image }}</span>
                    </div>
                    <div v-if="changelogLink" class="mt-3">
                        <h5>{{ $t("changelog") }}</h5>
                        <a :href="changelogLink" target="_blank">{{ changelogLink }}</a>
                    </div>

                    <BForm class="mt-3">
                        <BFormCheckbox v-model="updateDialogData.pruneAfterUpdate" switch><span v-html="$t('pruneAfterUpdate')"></span></BFormCheckbox>
                        <div style="margin-left: 2.5rem;">
                            <BFormCheckbox v-model="updateDialogData.pruneAllAfterUpdate" :checked="updateDialogData.pruneAfterUpdate && updateDialogData.pruneAllAfterUpdate" :disabled="!updateDialogData.pruneAfterUpdate"><span v-html="$t('pruneAllAfterUpdate')"></span></BFormCheckbox>
                        </div>
                    </BForm>

                    <template #footer>
                        <button class="btn btn-normal" data-toggle="tooltip" :title="$t('tooltipServiceUpdateIgnore')" @click="skipCurrentUpdate">
                            <font-awesome-icon icon="ban" class="me-1" />{{ $t("ignoreUpdate") }}
                        </button>
                        <button class="btn btn-primary" data-toggle="tooltip" :title="$t('tooltipDoServiceUpdate')" @click="updateService">
                            <font-awesome-icon icon="cloud-arrow-down" class="me-1" />{{ $t("updateStack") }}
                        </button>
                    </template>
                </BModal>

                <button
                    v-if="!isEditMode"
                    v-b-modal="eventLogModalId"
                    class="btn btn-sm btn-normal me-2"
                    data-toggle="tooltip" :title="$t('serviceEventLog')"
                    @click="fetchEventLog"
                >
                    <font-awesome-icon icon="clipboard-list" />
                </button>

                <!-- Service event log modal -->
                <BModal :id="eventLogModalId" :ref="eventLogModalId" :title="$t('serviceEventLog')" size="lg">
                    <div v-if="eventLogLoading" class="text-center py-3">
                        <span class="spinner-border spinner-border-sm me-2"></span>{{ $t('loading') }}
                    </div>
                    <div v-else-if="eventLogEntries.length === 0" class="text-muted text-center py-3">
                        {{ $t('noEventsYet') }}
                    </div>
                    <div v-else>
                        <div class="d-flex gap-4 mb-3">
                            <div v-if="lastRestart">
                                <div class="text-muted small">{{ $t('lastRestart') }}</div>
                                <div class="text-muted small">{{ formatRelativeTime(lastRestart.timestamp) }}</div>
                            </div>
                            <div v-if="lastUpdate">
                                <div class="text-muted small">{{ $t('lastUpdate') }}</div>
                                <div class="text-muted small">{{ formatRelativeTime(lastUpdate.timestamp) }}</div>
                            </div>
                            <div v-if="service.lastImageCheck">
                                <div class="text-muted small">{{ $t('lastImageCheck') }}</div>
                                <div class="text-muted small">{{ formatRelativeTime(service.lastImageCheck) }}</div>
                            </div>
                        </div>
                        <table class="table table-sm table-striped">
                            <thead>
                                <tr>
                                    <th>{{ $t('time') }}</th>
                                    <th>{{ $t('service') }}</th>
                                    <th>{{ $t('event') }}</th>
                                    <th>{{ $t('trigger') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="entry in eventLogEntries" :key="entry.id">
                                    <td class="text-nowrap" :title="formatAbsoluteTime(entry.timestamp)">{{ formatRelativeTime(entry.timestamp) }}</td>
                                    <td class="text-muted small">{{ entry.serviceName || $t('wholeStack') }}</td>
                                    <td>
                                        <span class="badge" :class="eventTypeBadge(entry.eventType)">{{ entry.eventType }}</span>
                                    </td>
                                    <td>
                                        <span class="badge" :class="triggerBadge(entry.trigger)">{{ entry.trigger }}</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <template #footer>
                        <button class="btn btn-normal" @click="(($refs[eventLogModalId]) as { hide(): void }).hide()">{{ $t('close') }}</button>
                    </template>
                </BModal>

                <div v-if="!isEditMode" class="btn-group me-2" role="group">
                    <router-link v-if="started" class="btn btn-sm btn-normal me-1" data-toggle="tooltip" :title="$t('tooltipServiceLog')" :to="logRouteLink" :disabled="processing"><font-awesome-icon icon="file-text" /></router-link>
                    <router-link v-if="started" class="btn btn-sm btn-normal me-1" data-toggle="tooltip" :title="$t('tooltipServiceInspect')" :to="inspectRouteLink" :disabled="processing"><font-awesome-icon icon="info-circle" /></router-link>
                    <router-link v-if="started" class="btn btn-sm btn-normal me-1" data-toggle="tooltip" :title="$t('tooltipServiceTerminal')" :to="terminalRouteLink" :disabled="processing"><font-awesome-icon icon="terminal" /></router-link>
                </div>

                <div v-if="!isEditMode" class="btn-group" role="group">
                    <button v-if="!started && !inactive" type="button" class="btn btn-sm btn-success" data-toggle="tooltip" :title="$t('tooltipServiceStart')" :disabled="processing" @click="startService"><font-awesome-icon icon="play" /></button>
                    <button v-if="started" type="button" class="btn btn-sm btn-danger me-1" data-toggle="tooltip" :title="$t('tooltipServiceStop')" :disabled="processing" @click="stopService"><font-awesome-icon icon="stop" /></button>
                    <button v-if="started" type="button" class="btn btn-sm btn-warning" data-toggle="tooltip" :title="$t('tooltipServiceRestart')" :disabled="processing" @click="restartService"><font-awesome-icon icon="rotate" /></button>
                </div>
            </div>
        </div>
        <div v-if="!isEditMode" class="row">
            <div v-if="service.recreateNecessary" class="notification mb-2">{{ $t("recreateNecessary") }}</div>
            <div class="d-flex flex-wrap justify-content-between gap-3 mb-2">
                <div class="image">
                    <span class="me-1">{{ composeService.imageName }}:</span><span class="tag">{{ composeService.imageTag }}</span>
                </div>
                <div v-if="started" class="status">
                    {{ service.status }}
                </div>
            </div>
        </div>

        <div v-if="!isEditMode" class="row">
            <div class="col">
                <span class="badge me-1" :class="bgStyle">{{ status }}</span>

                <a v-for="port in composeService.get('ports', [], true)" :key="port" :href="parsePort(port).url" target="_blank">
                    <span v-if="started" class="badge me-1 bg-secondary">{{ parsePort(port).display }}</span>
                </a>
            </div>
        </div>
        <div v-if="!isEditMode && stats" class="mt-2">
            <div class="d-flex align-items-start gap-3">
                <span class="stats-select" @click="expandedStats = !expandedStats">
                    <font-awesome-icon :icon="expandedStats ? 'chevron-circle-down' : 'chevron-circle-right'" />
                </span>
                <template v-if="!expandedStats">
                    <div class="stats">
                        {{ $t('CPU') }}: {{ stats.cpuPerc }}
                    </div>
                    <div class="stats">
                        {{ $t('memoryAbbreviated') }}: {{ stats.memUsage }}
                    </div>
                </template>
            </div>
            <transition name="slide-fade" appear>
                <div v-if="expandedStats" class="d-flex flex-column gap-3 mt-2">
                    <DockerStats :stats="stats" />
                </div>
            </transition>
        </div>

        <div v-if="isEditMode" class="mt-2">
            <button class="btn btn-normal me-2" @click="showConfig = !showConfig">
                <font-awesome-icon icon="edit" />
                {{ $t("Edit") }}
            </button>
            <button v-if="false" class="btn btn-normal me-2">Rename</button>
            <button class="btn btn-danger me-2" @click="remove">
                <font-awesome-icon icon="trash" />
                {{ $t("deleteContainer") }}
            </button>
        </div>

        <transition name="slide-fade" appear>
            <div v-if="isEditMode && showConfig" class="config mt-3">
                <!-- Image -->
                <div class="mb-4">
                    <h5>{{ $t("dockerImage") }}</h5>
                    <div class="input-group mt-3 mb-3">
                        <input
                            v-model="composeService.image"
                            class="form-control"
                            list="image-datalist"
                        />
                    </div>

                    <!-- TODO: Search online: https://hub.docker.com/api/content/v1/products/search?q=louislam%2Fuptime&source=community&page=1&page_size=4 -->
                    <datalist id="image-datalist">
                        <option value="louislam/uptime-kuma:1" />
                    </datalist>
                    <div class="form-text"></div>
                </div>

                <!-- Ports -->
                <div class="mb-4">
                    <h5>{{ $t("port", 2) }}</h5>
                    <ArrayInput :composeArray="composeService.ports" :display-name="$t('port')" placeholder="HOST:CONTAINER" />
                </div>

                <!-- Volumes -->
                <div class="mb-4">
                    <h5>{{ $t("volume", 2) }}</h5>
                    <ArrayInput :composeArray="composeService.volumes" :display-name="$t('volume')" placeholder="HOST:CONTAINER" />
                </div>

                <!-- Restart Policy -->
                <div class="mb-4">
                    <h5>{{ $t("restartPolicy") }}</h5>
                    <select v-model="composeService.restart" class="form-select mt-3">
                        <option value="always">{{ $t("restartPolicyAlways") }}</option>
                        <option value="unless-stopped">{{ $t("restartPolicyUnlessStopped") }}</option>
                        <option value="on-failure">{{ $t("restartPolicyOnFailure") }}</option>
                        <option value="no">{{ $t("restartPolicyNo") }}</option>
                    </select>
                </div>

                <!-- Environment Variables -->
                <div class="mb-4">
                    <h5>{{ $t("environmentVariable", 2) }}</h5>
                    <!-- TODO environmap kann auch Map sein -->
                    <ArrayInput :composeArray="composeService.environment" :display-name="$t('environmentVariable')" placeholder="KEY=VALUE" />
                </div>

                <!-- Container Name -->
                <div v-if="false" class="mb-4">
                    <h5>{{ $t("containerName") }}</h5>
                    <div class="input-group mb-3">
                        <input
                            v-model="composeService.containerName"
                            class="form-control"
                        />
                    </div>
                    <div class="form-text"></div>
                </div>

                <!-- Network -->
                <div class="mb-4">
                    <h5>{{ $t("network", 2) }}</h5>

                    <div v-if="composeDocument.networks.isEmpty() && !composeService.networks.isEmpty()" class="text-warning mb-3">
                        {{ $t("NoNetworksAvailable") }}
                    </div>

                    <ArraySelect :composeArray="composeService.networks" :display-name="$t('network')" placeholder="Network Name" :options="composeDocument.networks.names" />
                </div>

                <!-- Depends on -->
                <div class="mb-4">
                    <h5>{{ $t("dependsOn") }}</h5>
                    <ArrayInput :composeArray="composeService.dependsOn" :display-name="$t('dependsOn')" :placeholder="$t(`containerName`)" />
                </div>

                <!-- Arbour specific settings -->
                <div class="mb-4">
                    <h5>Arbour</h5>
                    <div class="form-check form-switch ms-2 mt-3">
                        <input
                            id="ignoreStatus"
                            class="form-check-input"
                            type="checkbox"
                            :checked="ignoreStatus"
                            @input="updateIgnoreStatus((($event.target) as any)?.checked)"
                        />
                        <label class="form-check-label" for="ignoreStatus">
                            {{ $t("ignoreStatus") }}
                        </label>
                    </div>
                    <div class="form-check form-switch ms-2 mt-3">
                        <input
                            id="checkImageUpdates"
                            class="form-check-input"
                            type="checkbox"
                            :checked="checkImageUpdates"
                            @input="updateCheckImageUpdates((($event.target) as any)?.checked)"
                        />
                        <label class="form-check-label" for="checkImageUpdates">
                            {{ $t("checkImageUpdates") }}
                        </label>
                    </div>
                    <div class="input-group mt-3">
                        <input
                            :value="changelogLink"
                            class="form-control"
                            @input="updateChangelogLink(($event.target as any)?.value)"
                        />
                    </div>
                    <div class="form-text ms-3">{{ $t("changelogLink") }}</div>
                </div>
            </div>
        </transition>
    </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { parseDockerPort } from "../../../common/util-common";
import { ServiceData, StatsData, StackData, ServiceEventEntry } from "../../../common/types";
import { ComposeDocument, ComposeService } from "../../../common/compose-document";
import { LABEL_STATUS_IGNORE, LABEL_IMAGEUPDATES_CHECK, LABEL_IMAGEUPDATES_IGNORE, LABEL_IMAGEUPDATES_CHANGELOG } from "../../../common/compose-labels";
import type { SocketRes } from "../vue-augmentation";

interface ComposePage {
    endpoint: string;
    stack: StackData;
    composeDocument: ComposeDocument;
    processing: boolean;
    startComposeAction(): void;
    stopComposeAction(): void;
    saveStack(): void;
}

export default defineComponent({
    components: {
        FontAwesomeIcon,
    },

    props: {
        name: {
            type: String,
            required: true,
        },
        isEditMode: {
            type: Boolean,
            default: false,
        },
        service: {
            type: Object as PropType<ServiceData>,
            default: {} as ServiceData,
        },
        stats: {
            type: Object as PropType<StatsData>,
            default: undefined,
        }
    },

    emits: [
    ],

    data() {
        return {
            showConfig: false,
            expandedStats: false,
            updateDialogData: {
                pruneAfterUpdate: false,
                pruneAllAfterUpdate: false
            },
            eventLogEntries: [] as ServiceEventEntry[],
            eventLogLoading: false,
        };
    },

    computed: {

        status(): string {
            const healthStatus = this.service.health;
            return !!healthStatus ? healthStatus : (this.inactive ? "inactive" : this.service.state);
        },

        bgStyle(): string {
            if (this.status === "running" || this.status === "healthy") {
                return "bg-primary";
            } else if (this.status === "unhealthy") {
                return "bg-danger";
            } else if (this.status === "inactive") {
                return "bg-dark";
            } else {
                return "bg-secondary";
            }
        },

        started(): boolean {
            return this.status === "starting" || this.status === "running" || this.status === "healthy" || this.status === "unhealthy" || this.status === "stopping";
        },

        inactive(): boolean {
            return Object.keys(this.service).length === 0;
        },

        logRouteLink() {
            if (this.endpoint) {
                return {
                    name: "containerLogEndpoint",
                    params: {
                        endpoint: this.endpoint,
                        stackName: this.stackName,
                        serviceName: this.name,
                    },
                };
            } else {
                return {
                    name: "containerLog",
                    params: {
                        stackName: this.stackName,
                        serviceName: this.name,
                    },
                };
            }
        },

        inspectRouteLink() {
            if (this.endpoint) {
                return {
                    name: "containerInspectEndpoint",
                    params: {
                        endpoint: this.endpoint,
                        containerName: this.service.containerName,
                    },
                };
            } else {
                return {
                    name: "containerInspect",
                    params: {
                        containerName: this.service.containerName,
                    },
                };
            }
        },

        terminalRouteLink() {
            if (this.endpoint) {
                return {
                    name: "containerTerminalEndpoint",
                    params: {
                        endpoint: this.endpoint,
                        stackName: this.stackName,
                        serviceName: this.name,
                        type: "bash",
                    },
                };
            } else {
                return {
                    name: "containerTerminal",
                    params: {
                        stackName: this.stackName,
                        serviceName: this.name,
                        type: "bash",
                    },
                };
            }
        },

        composePage(): ComposePage {
            return this.$parent!.$parent as unknown as ComposePage;
        },

        endpoint(): string {
            return this.composePage.endpoint;
        },

        stack(): StackData {
            return this.composePage.stack;
        },

        stackName(): string {
            return this.stack.name;
        },

        composeDocument(): ComposeDocument {
            return this.composePage.composeDocument;
        },

        composeService(this: { composeDocument: ComposeDocument, name: string }): ComposeService {
            return this.composeDocument.services.getService(this.name);
        },

        updateModalId(): string {
            return "image-update-modal-" + this.name;
        },

        eventLogModalId(): string {
            return "event-log-modal-" + this.name;
        },

        lastRestart(): ServiceEventEntry | null {
            return this.eventLogEntries.find(e => e.eventType === "restart" || e.eventType === "start") ?? null;
        },

        lastUpdate(): ServiceEventEntry | null {
            return this.eventLogEntries.find(e => e.eventType === "update") ?? null;
        },

        ignoreStatus(this: { composeService: ComposeService }): boolean {
            return this.composeService.labels.isTrue(LABEL_STATUS_IGNORE);
        },

        checkImageUpdates(this: {composeService: ComposeService}): boolean {
            return !this.composeService.labels.isFalse(LABEL_IMAGEUPDATES_CHECK);
        },

        changelogLink(this: {composeService: ComposeService}): string {
            return this.composeService.labels.get(LABEL_IMAGEUPDATES_CHANGELOG, "");
        },

        processing(): boolean {
            return this.composePage.processing;
        }
    },
    mounted() {
    },
    methods: {
        resetUpdateDialog() {
            this.updateDialogData = {
                pruneAfterUpdate: false,
                pruneAllAfterUpdate: false
            };
        },

        fetchEventLog() {
            this.eventLogLoading = true;
            this.$root.emitAgent(this.endpoint, "getServiceEventLog", this.stackName, this.name, (res: SocketRes) => {
                this.eventLogLoading = false;
                if (res.ok) {
                    this.eventLogEntries = res.events as ServiceEventEntry[];
                }
            });
        },

        formatRelativeTime(timestamp: number): string {
            const diff = Date.now() - timestamp;
            const seconds = Math.floor(diff / 1000);
            if (seconds < 60) {
                return `${seconds}s ago`;
            }
            const minutes = Math.floor(seconds / 60);
            if (minutes < 60) {
                return `${minutes}m ago`;
            }
            const hours = Math.floor(minutes / 60);
            if (hours < 24) {
                return `${hours}h ago`;
            }
            const days = Math.floor(hours / 24);
            return `${days}d ago`;
        },

        formatAbsoluteTime(timestamp: number): string {
            return new Date(timestamp).toLocaleString();
        },

        eventTypeBadge(eventType: string): string {
            const map: Record<string, string> = {
                update: "bg-primary",
                deploy: "bg-success",
                restart: "bg-warning text-dark",
                recreate: "bg-info text-dark",
                start: "bg-success",
                stop: "bg-secondary",
                down: "bg-dark",
            };
            return map[eventType] ?? "bg-secondary";
        },

        triggerBadge(trigger: string): string {
            const map: Record<string, string> = {
                manual: "bg-secondary",
                scheduled: "bg-info text-dark",
                immediate: "bg-warning text-dark",
            };
            return map[trigger] ?? "bg-secondary";
        },

        startComposeAction() {
            this.composePage.startComposeAction();
        },

        stopComposeAction() {
            this.composePage.stopComposeAction();
        },

        parsePort(port: string) {
            if (this.stack.endpoint) {
                return parseDockerPort(port, this.stack.primaryHostname);
            } else {
                let hostname = this.$root.info.primaryHostname as string || location.hostname;
                return parseDockerPort(port, hostname);
            }
        },
        remove() {
            this.composeDocument.services.delete(this.name);
        },
        stopService() {
            this.startComposeAction();
            this.$root.emitAgent(this.endpoint, "stopService", this.stack.name, this.name, (res: SocketRes) => {
                this.stopComposeAction();
                this.$root.toastRes(res);
            });
        },
        startService() {
            this.startComposeAction();
            this.$root.emitAgent(this.endpoint, "startService", this.stack.name, this.name, (res: SocketRes) => {
                this.stopComposeAction();
                this.$root.toastRes(res);
            });
        },
        restartService() {
            this.startComposeAction();
            this.$root.emitAgent(this.endpoint, "restartService", this.stack.name, this.name, (res: SocketRes) => {
                this.stopComposeAction();
                this.$root.toastRes(res);
            });
        },
        recreateService() {
            this.startComposeAction();
            this.$root.emitAgent(this.endpoint, "recreateService", this.stack.name, this.name, (res: SocketRes) => {
                this.stopComposeAction();
                this.$root.toastRes(res);
            });
        },
        updateService() {
            (this.$refs[this.updateModalId] as { hide(): void }).hide();

            this.startComposeAction();
            this.$root.emitAgent(this.endpoint, "updateService", this.stack.name, this.name, this.updateDialogData.pruneAfterUpdate, this.updateDialogData.pruneAllAfterUpdate, (res: SocketRes) => {
                this.stopComposeAction();
                this.$root.toastRes(res);
            });
        },
        skipCurrentUpdate() {
            (this.$refs[this.updateModalId] as { hide(): void }).hide();

            this.composeService.labels.set(LABEL_IMAGEUPDATES_IGNORE, this.service.remoteImageDigest);

            this.$nextTick(() => {
                // Wait for the adaptation of the Yaml
                this.composePage.saveStack();
            });
        },
        updateIgnoreStatus(checked: boolean) {
            const labels = this.composeService.labels;
            if (checked) {
                labels.set(LABEL_STATUS_IGNORE, true);
            } else {
                labels.delete(LABEL_STATUS_IGNORE);
                labels.removeIfEmpty();
            }
        },
        updateChangelogLink(link: string) {
            const labels = this.composeService.labels;
            if (link) {
                labels.set(LABEL_IMAGEUPDATES_CHANGELOG, link);
            } else {
                labels.delete(LABEL_IMAGEUPDATES_CHANGELOG);
                labels.removeIfEmpty();
            }
        },
        updateCheckImageUpdates(checked: boolean) {
            const labels = this.composeService.labels;
            if (checked) {
                labels.delete(LABEL_IMAGEUPDATES_CHECK);
                labels.removeIfEmpty();
            } else {
                labels.set(LABEL_IMAGEUPDATES_CHECK, false);
            }
        }
    }
});
</script>

<style scoped>

.container {
    max-width: 100%;

    .service-header {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        column-gap: 12px;
        row-gap: 6px;
        margin-bottom: 8px;

        .service-title {
            margin: 0;
            margin-right: auto;
        }

        .service-actions {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            gap: 4px;
            flex-shrink: 0;
        }
    }

    .image {
        font-size: 0.8rem;
        color: var(--arbour-text-muted);
        .tag {
            color: var(--arbour-text-muted);
        }
    }

    .status {
        font-size: 0.8rem;
        color: var(--arbour-text-muted);
    }

    .notification {
        font-size: 1rem;
        color: var(--arbour-danger);
    }

    .function {
        align-content: center;
        display: flex;
        height: 100%;
        width: 100%;
        align-items: center;
        justify-content: end;
    }

    .stats-select {
        cursor: pointer;
        font-size: 1rem;
        color: var(--arbour-text-muted);
    }

    .stats {
        font-size: 0.8rem;
        color: var(--arbour-text-muted);
    }
}
</style>

// frontend/src/lib/components/Container.svelte
<script lang="ts">
import { getContext } from "svelte";
import { t } from "svelte-i18n";
import { tn } from "$lib/stores/lang.svelte";
import { socketStore } from "$lib/stores/socket.svelte";
import { COMPOSE_CONTEXT, type ComposeContext } from "$lib/context";
import { parseDockerPort } from "../../../../common/util-common";
import { LABEL_STATUS_IGNORE, LABEL_IMAGEUPDATES_CHECK, LABEL_IMAGEUPDATES_IGNORE, LABEL_IMAGEUPDATES_CHANGELOG } from "../../../../common/compose-labels";
import type { ServiceData, StatsData, ServiceEventEntry } from "../../../../common/types";
import Icon from "./Icon.svelte";
import Confirm from "./Confirm.svelte";
import DockerStats from "./DockerStats.svelte";
import ArrayInput from "./ArrayInput.svelte";
import ArraySelect from "./ArraySelect.svelte";

const {
    name,
    isEditMode = false,
    service = {} as ServiceData,
    stats = undefined,
} = $props<{
    name: string;
    isEditMode?: boolean;
    service?: ServiceData;
    stats?: StatsData;
}>();

const ctx = getContext<ComposeContext>(COMPOSE_CONTEXT);

let showConfig = $state(false);
let expandedStats = $state(false);
let updateDialogData = $state({ pruneAfterUpdate: false, pruneAllAfterUpdate: false });
let eventLogEntries = $state<ServiceEventEntry[]>([]);
let eventLogLoading = $state(false);
let showUpdateDialog = $state(false);
let showEventLogDialog = $state(false);
let updateDialogEl = $state<HTMLDialogElement | undefined>(undefined);
let eventLogDialogEl = $state<HTMLDialogElement | undefined>(undefined);

$effect(() => {
    if (!updateDialogEl) return;
    if (showUpdateDialog) updateDialogEl.showModal(); else updateDialogEl.close();
});
$effect(() => {
    if (!eventLogDialogEl) return;
    if (showEventLogDialog) eventLogDialogEl.showModal(); else eventLogDialogEl.close();
});

const inactive = $derived(Object.keys(service).length === 0);

const status = $derived(() => {
    const healthStatus = (service as ServiceData).health;
    return healthStatus ? healthStatus : (inactive ? "inactive" : (service as ServiceData).state);
});

const bgStyle = $derived(() => {
    const s = status();
    if (s === "running" || s === "healthy") return "badge-running";
    if (s === "unhealthy") return "bg-danger";
    if (s === "inactive") return "badge-inactive";
    return "bg-secondary";
});

const started = $derived(() => {
    const s = status();
    return s === "starting" || s === "running" || s === "healthy" || s === "unhealthy" || s === "stopping";
});

const composeService = $derived(ctx.composeDocument.services.getService(name));

const ignoreStatus = $derived(composeService.labels.isTrue(LABEL_STATUS_IGNORE));
const checkImageUpdates = $derived(!composeService.labels.isFalse(LABEL_IMAGEUPDATES_CHECK));
const changelogLink = $derived(composeService.labels.get(LABEL_IMAGEUPDATES_CHANGELOG, ""));

const lastRestart = $derived(eventLogEntries.find(e => e.eventType === "restart" || e.eventType === "start") ?? null);
const lastUpdate = $derived(eventLogEntries.find(e => e.eventType === "update") ?? null);

function logLink() {
    return ctx.endpoint
        ? `/log/${ctx.stack.name}/${name}/${ctx.endpoint}`
        : `/log/${ctx.stack.name}/${name}`;
}

function inspectLink() {
    const containerName = (service as ServiceData).containerName;
    return ctx.endpoint
        ? `/inspect/${containerName}/${ctx.endpoint}`
        : `/inspect/${containerName}`;
}

function terminalLink() {
    return ctx.endpoint
        ? `/terminal/${ctx.stack.name}/${name}/bash/${ctx.endpoint}`
        : `/terminal/${ctx.stack.name}/${name}/bash`;
}

function parsePort(port: string) {
    if (ctx.stack.endpoint) {
        return parseDockerPort(port, ctx.stack.primaryHostname);
    }
    const hostname = socketStore.info.primaryHostname as string || location.hostname;
    return parseDockerPort(port, hostname);
}

function fetchEventLog() {
    eventLogLoading = true;
    socketStore.emitAgent(ctx.endpoint, "getServiceEventLog", ctx.stack.name, name, (res: { ok: boolean; events?: ServiceEventEntry[] }) => {
        eventLogLoading = false;
        if (res.ok) eventLogEntries = res.events ?? [];
    });
}

function formatRelativeTime(timestamp: number): string {
    const diff = Date.now() - timestamp;
    const seconds = Math.floor(diff / 1000);
    if (seconds < 60) return `${seconds}s ago`;
    const minutes = Math.floor(seconds / 60);
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    return `${Math.floor(hours / 24)}d ago`;
}

function formatAbsoluteTime(timestamp: number): string {
    return new Date(timestamp).toLocaleString();
}

function eventTypeBadge(eventType: string): string {
    const map: Record<string, string> = {
        update: "ev-primary", deploy: "ev-success", restart: "ev-warning",
        recreate: "ev-info", start: "ev-success", stop: "ev-secondary", down: "ev-dark",
    };
    return map[eventType] ?? "ev-secondary";
}

function triggerBadge(trigger: string): string {
    const map: Record<string, string> = {
        manual: "ev-secondary", scheduled: "ev-info", immediate: "ev-warning",
    };
    return map[trigger] ?? "ev-secondary";
}

function stopService() {
    ctx.startComposeAction();
    socketStore.emitAgent(ctx.endpoint, "stopService", ctx.stack.name, name, (res: { ok: boolean; msg?: string }) => {
        ctx.stopComposeAction();
        socketStore.toastRes(res as any);
    });
}

function startService() {
    ctx.startComposeAction();
    socketStore.emitAgent(ctx.endpoint, "startService", ctx.stack.name, name, (res: { ok: boolean; msg?: string }) => {
        ctx.stopComposeAction();
        socketStore.toastRes(res as any);
    });
}

function restartService() {
    ctx.startComposeAction();
    socketStore.emitAgent(ctx.endpoint, "restartService", ctx.stack.name, name, (res: { ok: boolean; msg?: string }) => {
        ctx.stopComposeAction();
        socketStore.toastRes(res as any);
    });
}

function recreateService() {
    ctx.startComposeAction();
    socketStore.emitAgent(ctx.endpoint, "recreateService", ctx.stack.name, name, (res: { ok: boolean; msg?: string }) => {
        ctx.stopComposeAction();
        socketStore.toastRes(res as any);
    });
}

function updateService() {
    showUpdateDialog = false;
    ctx.startComposeAction();
    socketStore.emitAgent(ctx.endpoint, "updateService", ctx.stack.name, name,
        updateDialogData.pruneAfterUpdate, updateDialogData.pruneAllAfterUpdate,
        (res: { ok: boolean; msg?: string }) => {
            ctx.stopComposeAction();
            socketStore.toastRes(res as any);
        });
}

function skipCurrentUpdate() {
    showUpdateDialog = false;
    composeService.labels.set(LABEL_IMAGEUPDATES_IGNORE, (service as ServiceData).remoteImageDigest);
    ctx.saveStack();
}

function remove() {
    ctx.composeDocument.services.delete(name);
}

function updateIgnoreStatus(checked: boolean) {
    if (checked) {
        composeService.labels.set(LABEL_STATUS_IGNORE, true);
    } else {
        composeService.labels.delete(LABEL_STATUS_IGNORE);
        composeService.labels.removeIfEmpty();
    }
}

function updateCheckImageUpdates(checked: boolean) {
    if (checked) {
        composeService.labels.delete(LABEL_IMAGEUPDATES_CHECK);
        composeService.labels.removeIfEmpty();
    } else {
        composeService.labels.set(LABEL_IMAGEUPDATES_CHECK, false);
    }
}

function updateChangelogLink(link: string) {
    if (link) {
        composeService.labels.set(LABEL_IMAGEUPDATES_CHANGELOG, link);
    } else {
        composeService.labels.delete(LABEL_IMAGEUPDATES_CHANGELOG);
        composeService.labels.removeIfEmpty();
    }
}
</script>

<div class="shadow-box big-padding mb-3 container">
    <div class="service-header">
        <h4 class="service-title">{name}</h4>
        <div class="service-actions">
            {#if !isEditMode && (service as ServiceData).recreateNecessary}
                <button class="btn btn-sm btn-info" title={$t("tooltipServiceRecreate")}
                    disabled={ctx.processing} onclick={recreateService}>
                    <Icon name="rocket" />
                </button>
            {/if}

            {#if !isEditMode && (service as ServiceData).imageUpdateAvailable}
                <button class="btn btn-sm btn-info" title={$t("tooltipServiceUpdate")}
                    disabled={ctx.processing} onclick={() => (showUpdateDialog = true)}>
                    <Icon name="arrow-up" />
                </button>
            {/if}

            {#if !isEditMode}
                <button class="btn btn-sm btn-normal" title={$t("serviceEventLog")}
                    onclick={() => { fetchEventLog(); showEventLogDialog = true; }}>
                    <Icon name="clipboard-list" />
                </button>
            {/if}

            {#if !isEditMode && started()}
                <div class="btn-group">
                    <a class="btn btn-sm btn-normal" title={$t("tooltipServiceLog")} href={logLink()}>
                        <Icon name="file-lines" />
                    </a>
                    <a class="btn btn-sm btn-normal" title={$t("tooltipServiceInspect")} href={inspectLink()}>
                        <Icon name="circle-info" />
                    </a>
                    <a class="btn btn-sm btn-normal" title={$t("tooltipServiceTerminal")} href={terminalLink()}>
                        <Icon name="terminal" />
                    </a>
                </div>
            {/if}

            {#if !isEditMode}
                <div class="btn-group">
                    {#if !started() && !inactive}
                        <button type="button" class="btn btn-sm btn-success" title={$t("tooltipServiceStart")}
                            disabled={ctx.processing} onclick={startService}>
                            <Icon name="play" />
                        </button>
                    {/if}
                    {#if started()}
                        <button type="button" class="btn btn-sm btn-danger" title={$t("tooltipServiceStop")}
                            disabled={ctx.processing} onclick={stopService}>
                            <Icon name="stop" />
                        </button>
                        <button type="button" class="btn btn-sm btn-warning" title={$t("tooltipServiceRestart")}
                            disabled={ctx.processing} onclick={restartService}>
                            <Icon name="rotate" />
                        </button>
                    {/if}
                </div>
            {/if}
        </div>
    </div>

    {#if !isEditMode}
        {#if (service as ServiceData).recreateNecessary}
            <div class="notification">{$t("recreateNecessary")}</div>
        {/if}
        <div class="service-meta">
            <div class="image-label">
                <span>{composeService.imageName}:</span><span class="tag">{composeService.imageTag}</span>
            </div>
            {#if started()}
                <div class="status-text">{(service as ServiceData).status}</div>
            {/if}
        </div>
        <div class="badges">
            <span class="badge {bgStyle()}">{status()}</span>
            {#if started()}
                {#each composeService.get("ports", [], true) as port (port)}
                    <a href={parsePort(port).url} target="_blank">
                        <span class="badge bg-secondary">{parsePort(port).display}</span>
                    </a>
                {/each}
            {/if}
        </div>

        {#if stats}
            <div class="stats-row">
                <button class="stats-toggle" onclick={() => (expandedStats = !expandedStats)}>
                    <Icon name={expandedStats ? "chevron-down" : "chevron-right"} />
                </button>
                {#if !expandedStats}
                    <span class="stat">{$t("CPU")}: {stats.cpuPerc}</span>
                    <span class="stat">{$t("memoryAbbreviated")}: {stats.memUsage}</span>
                {:else}
                    <DockerStats {stats} />
                {/if}
            </div>
        {/if}
    {/if}

    {#if isEditMode}
        <div class="edit-actions">
            <button class="btn btn-sm btn-normal" onclick={() => (showConfig = !showConfig)}>
                <Icon name="pen-to-square" /> {$t("Edit")}
            </button>
            <button class="btn btn-sm btn-danger" onclick={remove}>
                <Icon name="trash" /> {$t("deleteContainer")}
            </button>
        </div>

        {#if showConfig}
            <div class="config">
                <div class="config-section">
                    <h5>{$t("dockerImage")}</h5>
                    <input class="form-control" bind:value={composeService.image} list="image-datalist-{name}" />
                    <datalist id="image-datalist-{name}">
                        <option value="louislam/uptime-kuma:1"></option>
                    </datalist>
                </div>

                <div class="config-section">
                    <h5>{$tn("port", 2)}</h5>
                    <ArrayInput composeArray={composeService.ports} displayName={$t("port")} placeholder="HOST:CONTAINER" />
                </div>

                <div class="config-section">
                    <h5>{$tn("volume", 2)}</h5>
                    <ArrayInput composeArray={composeService.volumes} displayName={$t("volume")} placeholder="HOST:CONTAINER" />
                </div>

                <div class="config-section">
                    <h5>{$t("restartPolicy")}</h5>
                    <select class="form-select" bind:value={composeService.restart}>
                        <option value="always">{$t("restartPolicyAlways")}</option>
                        <option value="unless-stopped">{$t("restartPolicyUnlessStopped")}</option>
                        <option value="on-failure">{$t("restartPolicyOnFailure")}</option>
                        <option value="no">{$t("restartPolicyNo")}</option>
                    </select>
                </div>

                <div class="config-section">
                    <h5>{$tn("environmentVariable", 2)}</h5>
                    <ArrayInput composeArray={composeService.environment} displayName={$t("environmentVariable")} placeholder="KEY=VALUE" />
                </div>

                <div class="config-section">
                    <h5>{$tn("network", 2)}</h5>
                    {#if ctx.composeDocument.networks.isEmpty() && !composeService.networks.isEmpty()}
                        <p class="warn">{$t("NoNetworksAvailable")}</p>
                    {/if}
                    <ArraySelect composeArray={composeService.networks} displayName={$t("network")} options={ctx.composeDocument.networks.names} />
                </div>

                <div class="config-section">
                    <h5>{$t("dependsOn")}</h5>
                    <ArrayInput composeArray={composeService.dependsOn} displayName={$t("dependsOn")} placeholder={$t("containerName")} />
                </div>

                <div class="config-section">
                    <h5>Arbour</h5>
                    <div class="form-check form-switch">
                        <input id="ignore-status-{name}" class="form-check-input" type="checkbox" checked={ignoreStatus}
                            onchange={(e) => updateIgnoreStatus((e.target as HTMLInputElement).checked)} />
                        <label class="form-check-label" for="ignore-status-{name}">{$t("ignoreStatus")}</label>
                    </div>
                    <div class="form-check form-switch">
                        <input id="check-img-{name}" class="form-check-input" type="checkbox" checked={checkImageUpdates}
                            onchange={(e) => updateCheckImageUpdates((e.target as HTMLInputElement).checked)} />
                        <label class="form-check-label" for="check-img-{name}">{$t("checkImageUpdates")}</label>
                    </div>
                    <input class="form-control" value={changelogLink}
                        oninput={(e) => updateChangelogLink((e.target as HTMLInputElement).value)} />
                    <div class="form-text">{$t("changelogLink")}</div>
                </div>
            </div>
        {/if}
    {/if}
</div>

<!-- Image update dialog -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<dialog bind:this={updateDialogEl} class="update-dialog" onclose={() => (showUpdateDialog = false)}
    onclick={(e) => { if (e.target === e.currentTarget) showUpdateDialog = false; }}>
    <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{$tn("imageUpdate", 1)}</h5>
                <button class="btn-close" aria-label="Close" onclick={() => (showUpdateDialog = false)}></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <h6>{$t("image")}</h6>
                    <span>{composeService.image}</span>
                </div>
                {#if changelogLink}
                    <div class="mb-3">
                        <h6>{$t("changelog")}</h6>
                        <a href={changelogLink} target="_blank">{changelogLink}</a>
                    </div>
                {/if}
                <div class="form-check">
                    <input id="prune-after-{name}" class="form-check-input" type="checkbox" bind:checked={updateDialogData.pruneAfterUpdate} />
                    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
                    <label class="form-check-label" for="prune-after-{name}">{@html $t("pruneAfterUpdate")}</label>
                </div>
                <div class="ms-3">
                    <div class="form-check">
                        <input id="prune-all-{name}" class="form-check-input" type="checkbox"
                            checked={updateDialogData.pruneAfterUpdate && updateDialogData.pruneAllAfterUpdate}
                            disabled={!updateDialogData.pruneAfterUpdate}
                            onchange={(e) => (updateDialogData.pruneAllAfterUpdate = (e.target as HTMLInputElement).checked)} />
                        <!-- eslint-disable-next-line svelte/no-at-html-tags -->
                        <label class="form-check-label" for="prune-all-{name}">{@html $t("pruneAllAfterUpdate")}</label>
                    </div>
                </div>
            </div>
        <div class="modal-footer">
            <button class="btn btn-normal" title={$t("tooltipServiceUpdateIgnore")} onclick={skipCurrentUpdate}>
                <Icon name="ban" /> {$t("ignoreUpdate")}
            </button>
            <button class="btn btn-primary" title={$t("tooltipDoServiceUpdate")} onclick={updateService}>
                <Icon name="cloud-arrow-down" /> {$t("updateStack")}
            </button>
        </div>
    </div>
</dialog>

<!-- Event log dialog -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<dialog bind:this={eventLogDialogEl} class="event-log-dialog" onclose={() => (showEventLogDialog = false)}
    onclick={(e) => { if (e.target === e.currentTarget) showEventLogDialog = false; }}>
    <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{$t("serviceEventLog")}</h5>
                <button class="btn-close" aria-label="Close" onclick={() => (showEventLogDialog = false)}></button>
            </div>
            <div class="modal-body">
                {#if eventLogLoading}
                    <div class="loading-state"><Icon name="spinner" spin={true} /> {$t("loading")}</div>
                {:else if eventLogEntries.length === 0}
                    <div class="empty-state">{$t("noEventsYet")}</div>
                {:else}
                    <div class="event-summary">
                        {#if lastRestart}
                            <div>
                                <div class="summary-label">{$t("lastRestart")}</div>
                                <div class="summary-val">{formatRelativeTime(lastRestart.timestamp)}</div>
                            </div>
                        {/if}
                        {#if lastUpdate}
                            <div>
                                <div class="summary-label">{$t("lastUpdate")}</div>
                                <div class="summary-val">{formatRelativeTime(lastUpdate.timestamp)}</div>
                            </div>
                        {/if}
                        {#if (service as ServiceData).lastImageCheck}
                            <div>
                                <div class="summary-label">{$t("lastImageCheck")}</div>
                                <div class="summary-val">{formatRelativeTime((service as ServiceData).lastImageCheck!)}</div>
                            </div>
                        {/if}
                    </div>
                    <table class="table table-sm table-striped">
                        <thead>
                            <tr>
                                <th>{$t("time")}</th>
                                <th>{$t("service")}</th>
                                <th>{$t("event")}</th>
                                <th>{$t("trigger")}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {#each eventLogEntries as entry (entry.id)}
                                <tr>
                                    <td class="text-nowrap" title={formatAbsoluteTime(entry.timestamp)}>
                                        {formatRelativeTime(entry.timestamp)}
                                    </td>
                                    <td class="text-muted small">{entry.serviceName || $t("wholeStack")}</td>
                                    <td><span class="ev-badge {eventTypeBadge(entry.eventType)}">{entry.eventType}</span></td>
                                    <td><span class="ev-badge {triggerBadge(entry.trigger)}">{entry.trigger}</span></td>
                                </tr>
                            {/each}
                        </tbody>
                    </table>
                {/if}
            </div>
        <div class="modal-footer">
            <button class="btn btn-normal" onclick={() => (showEventLogDialog = false)}>{$t("close")}</button>
        </div>
    </div>
</dialog>

<style>
.service-header {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    column-gap: 12px;
    row-gap: 6px;
    margin-bottom: 8px;
}

.service-title {
    margin: 0;
    margin-right: auto;
    font-size: 1rem;
    font-weight: 600;
}

.service-actions {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px;
    flex-shrink: 0;
}

.notification { font-size: 0.9rem; color: var(--arbour-danger); margin-bottom: 0.5rem; }

.service-meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.8rem;
    color: var(--arbour-text-muted);
    margin-bottom: 4px;
}
.image-label .tag { color: var(--arbour-primary); }

.badges { display: flex; flex-wrap: wrap; gap: 4px; margin-bottom: 4px; }

.badge-running { background: var(--arbour-primary); color: var(--arbour-text-on-primary); }
.badge-inactive { background: var(--arbour-bg-header-active); color: var(--arbour-text-muted); }

.stats-row {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin-top: 0.5rem;
    font-size: 0.8rem;
}
.stats-toggle {
    background: none; border: none; color: var(--arbour-text-muted);
    cursor: pointer; padding: 0; font-size: 0.9rem;
}
.stat { color: var(--arbour-text-muted); }

.edit-actions { display: flex; gap: 0.5rem; margin-top: 0.5rem; flex-wrap: wrap; }

.config { margin-top: 1rem; display: flex; flex-direction: column; gap: 1.25rem; }
.config-section { display: flex; flex-direction: column; gap: 0.5rem; }
.config-section h5 { margin: 0; font-size: 0.9rem; font-weight: 600; }

.warn { color: var(--arbour-warning); font-size: 0.85rem; margin: 0; }

.status-text { font-size: 0.78rem; color: var(--arbour-text-muted); font-family: 'JetBrains Mono', monospace; }

.update-dialog { max-width: 480px; width: calc(100% - 2rem); }
.event-log-dialog { max-width: 800px; width: calc(100% - 2rem); }
.event-log-dialog .modal-body { max-height: 65vh; overflow-y: auto; }

.loading-state, .empty-state {
    padding: 1.5rem; text-align: center; color: var(--arbour-text-muted);
    display: flex; align-items: center; justify-content: center; gap: 0.5rem;
}

.event-summary {
    display: flex; gap: 1.5rem; margin-bottom: 1rem;
}
.summary-label { font-size: 0.75rem; color: var(--arbour-text-muted); }
.summary-val { font-size: 0.8rem; color: var(--arbour-text-muted); }

.small { font-size: 0.8rem; }

.ev-badge {
    display: inline-block; padding: 0.15em 0.4em;
    border-radius: var(--arbour-radius-pill); font-size: 0.72rem; font-weight: 600;
}
.ev-primary { background: var(--arbour-primary); color: var(--arbour-text-on-primary); }
.ev-success { background: var(--arbour-success); color: var(--arbour-text-on-primary); }
.ev-warning { background: var(--arbour-warning); color: var(--arbour-text-on-warning); }
.ev-info { background: var(--arbour-info); color: var(--arbour-text-on-primary); }
.ev-secondary { background: var(--arbour-bg-header-active); color: var(--arbour-text-muted); }
.ev-dark { background: var(--arbour-bg-deep); color: var(--arbour-text-muted); }
</style>
