// frontend/src/components/DockerArtefact.vue
<template>
    <div class="btn-group mb-3" role="group">
        <button v-if="artefact.actions.includes(DockerArtefactAction.Prune)" class="btn btn-primary btn-sm me-1" data-toggle="tooltip" :title="$t('tooltipOpenPruneDialog')" :disabled="processing" @click="showPruneDialog = true">
            <font-awesome-icon icon="wrench" class="me-1" />
            <span>{{ $t("prune") }}</span>
        </button>

        <button v-if="artefact.actions.includes(DockerArtefactAction.Pull)" class="btn btn-secondary btn-sm me-1" data-toggle="tooltip" :title="$t('tooltipPullSelected')" :disabled="processing || selectedItems.length === 0" @click="checkOpenPullDialog">
            <font-awesome-icon icon="cloud-arrow-down" class="me-1" />
            <span>{{ $t("pull") }}</span>
        </button>

        <button v-if="artefact.actions.includes(DockerArtefactAction.Remove)" class="btn btn-danger btn-sm" data-toggle="tooltip" :title="$t('tooltipDeleteSelected')" :disabled="processing || selectedItems.length === 0" @click="showDeleteDialog = true">
            <font-awesome-icon icon="trash" class="me-1" />
            <span>{{ $t("delete") }}</span>
        </button>
    </div>

    <!-- Prune dialog -->
    <BModal v-model="showPruneDialog" :title="$t('prune') + ' ' + $t(artefact.name, 2)" :no-close-on-backdrop="true" :close-on-esc="true" :okTitle="$t('prune')" okVariant="danger" @ok="executeAction(pruneDialogData.all ? DockerArtefactAction.PruneAll : DockerArtefactAction.Prune)" @show="resetPruneDialog" @hidden="resetPruneDialog">
        <p class="mb-3" v-html="$t(artefact.name + 'PruneMsg')"></p>

        <BForm v-if="artefact.actions.includes(DockerArtefactAction.PruneAll)">
            <BFormCheckbox v-model="pruneDialogData.all" switch>{{ $t(artefact.name + "PruneAll") }}</BFormCheckbox>
        </BForm>
    </BModal>

    <!-- Pull dialog -->
    <BModal v-model="showPullDialog" :title="$t('pull') + ' ' + $t(artefact.name, 2)" :no-close-on-backdrop="true" :close-on-esc="true" :okTitle="$t('pull')" okVariant="primary" :ok-disabled="selectedItems.length === 0" @ok="executeAction(DockerArtefactAction.Pull)">
        <p v-html="$t('imagePullInfoMsg')"></p>
        <p v-html="pullDialogData.danglingImagesList"></p>
    </BModal>

    <!-- Delete dialog -->
    <BModal v-model="showDeleteDialog" :title="$t('delete') + ' ' + $t(artefact.name, 2)" :no-close-on-backdrop="true" :close-on-esc="true" :okTitle="$t('delete')" okVariant="danger" @ok="executeAction(DockerArtefactAction.Remove)">
        <p class="mb-3" v-html="$t(artefact.name + 'DeleteMsg')"></p>
    </BModal>

    <!-- Network inspect modal (single instance, always mounted for network artefacts) -->
    <NetworkInspectModal
        v-if="artefact.name === 'network'"
        v-model="showNetworkInspect"
        :endpoint="endpoint"
        :network-id="inspectNetworkId"
    />

    <div v-if="fetchingData">{{ $t("fetchingData") }}</div>

    <div v-else class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th v-for="(title, index) in dataHeader" :key="index" class="sortable-header" scope="col" @click="toggleSort(title)">{{ title }} <span class="sort-symbol">{{ sortCol === title ? (sortDir === "UP" ? "&nbsp;▲" : "&nbsp;▼" ) : "&nbsp;&nbsp;" }}</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(item, itemIndex) in tableData" :key="itemIndex">
                    <td scope="col">
                        <input
                            v-model="selectedItems"
                            class="form-check-input"
                            type="checkbox"
                            :value="item.id"
                        />
                    </td>
                    <td v-for="(value, valueIndex) in item.values" :key="valueIndex" class="artefact-cell">{{ getValue(value) }}</td>
                    <td>
                        <span v-if="item.dangling" class="badge bg-info me-2">{{ item.danglingLabel }}</span>
                        <button
                            v-if="artefact.name === 'network'"
                            class="btn btn-sm btn-outline-secondary py-0 px-1"
                            :title="$t('networkInspect')"
                            @click="openNetworkInspect(item.id)"
                        >
                            <font-awesome-icon icon="circle-info" />
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<script lang="ts" setup>
import { computed, ref, Ref, reactive, onMounted, inject, getCurrentInstance } from "vue";
import { DockerArtefactAction, DockerArtefactData, DockerArtefactInfo, DockerArtefactItem } from "../../../common/types";
import NetworkInspectModal from "./NetworkInspectModal.vue";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const root = getCurrentInstance()?.proxy?.$root as any;

const props = defineProps<{
  endpoint: string;
  artefact: DockerArtefactInfo;
}>();

// Injected from parent
const processing = inject("processing") as Ref<boolean>;
const startAction = inject("startAction") as () => void;
const stopAction = inject("stopAction") as () => void;

// Local types
type SortDir = "UP" | "DOWN";

// Local reactive state
const fetchingData = ref(true);
const data = ref<DockerArtefactData>({
    info: props.artefact,
    data: []
});
const dataMap = reactive(new Map<string, DockerArtefactItem>());
const tableData = ref<DockerArtefactItem[]>([]);
const sortCol = ref<string>("");
const sortDir = ref<SortDir>("UP");
const selectedItems = ref<string[]>([]);
const showPruneDialog = ref(false);
const pruneDialogData = reactive({ all: false });
const showPullDialog = ref(false);
const pullDialogData = reactive({ danglingImagesList: "" });
const showDeleteDialog = ref(false);
const inspectNetworkId = ref<string>("");
const showNetworkInspect = ref(false);

// Computed
const dataHeader = computed(() => data.value.data.length > 0 ? Object.keys(data.value.data[0].values) : []);

// Methods
function loadData() {
    console.debug("Loading data for " + props.artefact.name);

    fetchingData.value = true;

    root.emitAgent(props.endpoint, "getDockerArtefactData", props.artefact.name, (res) => {
        fetchingData.value = false;

        data.value = res.data;
        dataMap.clear();
        for (const item of data.value.data) {
            dataMap.set(item.id, item);
        }

        if (sortCol.value === "") {
            sortCol.value = dataHeader.value.length > 0 ? dataHeader.value[0] : "";
        }
        sortData();

        selectedItems.value = [];
    });
}

function sortData() {
    if (sortCol.value !== "") {
        tableData.value = Array.from(dataMap.values()).sort((i1, i2) => {
            let v1 = getValue(i1.values[sortCol.value], true);
            let v2 = getValue(i2.values[sortCol.value], true);

            const upSort = sortDir.value === "UP";

            if (typeof (v1) === "string") {
                v2 = v2 as string;
                return (upSort ? v1 : v2).localeCompare(upSort ? v2 : v1);
            } else {
                v2 = v2 as number;
                return (upSort ? v1 : v2) - (upSort ? v2 : v1);
            }
        });
    }
}

function toggleSort(col: string) {
    if (sortCol.value != col) {
        sortCol.value = col;
        sortDir.value = "UP";
    } else {
        sortDir.value = (sortDir.value === "UP" ? "DOWN" : "UP");
    }

    sortData();
}

function getValue(value: string | [string, string] | [string, number], sortValue = false): string | number {
    if (Array.isArray(value)) {
        return sortValue ? value[1] : value[0];
    } else {
        return value;
    }
}

function openNetworkInspect(networkId: string) {
    inspectNetworkId.value = networkId;
    showNetworkInspect.value = true;
}

function resetPruneDialog() {
    pruneDialogData.all = false;
}

function checkOpenPullDialog() {
    const selectedDanglingImages = selectedItems.value
        .filter(id => dataMap.get(id)!.excludedActions.includes(DockerArtefactAction.Pull));

    if (selectedDanglingImages.length > 0) {
        const escape = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        const danglingImageList = [ "<ul>" ];
        for (const id of selectedDanglingImages) {
            danglingImageList.push(`<li>${escape(dataMap.get(id)!.actionIds.pull)}</li>`);
        }
        danglingImageList.push("</ul>");
        pullDialogData.danglingImagesList = danglingImageList.join("");

        selectedItems.value = selectedItems.value.filter(id => !selectedDanglingImages.includes(id));

        showPullDialog.value = true;
    } else {
        executeAction(DockerArtefactAction.Pull);
    }
}

function executeAction(action: DockerArtefactAction) {
    startAction?.();

    root.emitAgent(props.endpoint, "executeDockerArtefactAction", props.artefact.name, action, selectedItems.value.map(id => dataMap.get(id)?.actionIds[action] ?? id), (res) => {
        stopAction?.();
        root.toastRes(res);
        loadData();
    });
}

// Lifecycle
onMounted(() => {
    loadData();
});

</script>

<style lang="scss" scoped>
    @import "../styles/vars.scss";

    .artefact-cell {
        max-width: 200px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .sortable-header {
        cursor: pointer;
    }

    .sort-symbol {
        color: var(--arbour-text);
        font-family: monospace;
    }

</style>

// frontend/src/lib/components/DockerArtefact.svelte
<script lang="ts">
import { onMount, getContext } from "svelte";
import { t } from "svelte-i18n";
import { tn } from "$lib/stores/lang.svelte";
import { socketStore } from "$lib/stores/socket.svelte";
import { AGENT_CONTEXT, type AgentContext } from "$lib/context";
import Icon from "./Icon.svelte";
import Confirm from "./Confirm.svelte";
import NetworkInspectModal from "./NetworkInspectModal.svelte";
import { DockerArtefactAction, type DockerArtefactData, type DockerArtefactInfo, type DockerArtefactItem } from "../../../../common/types";

const { endpoint, artefact } = $props<{
    endpoint: string;
    artefact: DockerArtefactInfo;
}>();

const ctx = getContext<AgentContext>(AGENT_CONTEXT);

type SortDir = "UP" | "DOWN";

let fetchingData = $state(true);
let data = $state<DockerArtefactData>({ info: artefact, data: [] });
let dataMap = new Map<string, DockerArtefactItem>();
let tableData = $state<DockerArtefactItem[]>([]);
let sortCol = $state("");
let sortDir = $state<SortDir>("UP");
let selectedItems = $state<string[]>([]);

let showPruneDialog = $state(false);
let pruneAll = $state(false);
let showPullDialog = $state(false);
let pullDanglingList = $state("");
let showDeleteDialog = $state(false);

let inspectNetworkId = $state("");
let showNetworkInspect = $state(false);

const dataHeader = $derived(data.data.length > 0 ? Object.keys(data.data[0].values) : []);

function getValue(value: string | [string, string] | [string, number], sortValue = false): string | number {
    return Array.isArray(value) ? (sortValue ? value[1] : value[0]) : value;
}

function sortData() {
    if (!sortCol) return;
    tableData = Array.from(dataMap.values()).sort((i1, i2) => {
        const v1 = getValue(i1.values[sortCol], true);
        const v2 = getValue(i2.values[sortCol], true);
        const up = sortDir === "UP";
        if (typeof v1 === "string") {
            return (up ? v1 : v2 as string).localeCompare(up ? v2 as string : v1);
        }
        return (up ? v1 : v2 as number) - (up ? v2 as number : v1);
    });
}

export function loadData() {
    fetchingData = true;
    socketStore.emitAgent(endpoint, "getDockerArtefactData", artefact.name, (res: { ok: boolean; data: DockerArtefactData }) => {
        fetchingData = false;
        data = res.data;
        dataMap.clear();
        for (const item of data.data) dataMap.set(item.id, item);
        if (!sortCol) sortCol = dataHeader[0] ?? "";
        sortData();
        selectedItems = [];
    });
}

function toggleSort(col: string) {
    if (sortCol !== col) { sortCol = col; sortDir = "UP"; }
    else { sortDir = sortDir === "UP" ? "DOWN" : "UP"; }
    sortData();
}

function openNetworkInspect(networkId: string) {
    inspectNetworkId = networkId;
    showNetworkInspect = true;
}

function checkOpenPullDialog() {
    const dangling = selectedItems.filter(id => dataMap.get(id)!.excludedActions.includes(DockerArtefactAction.Pull));
    if (dangling.length > 0) {
        const escape = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        pullDanglingList = "<ul>" + dangling.map(id => `<li>${escape(dataMap.get(id)!.actionIds[DockerArtefactAction.Pull])}</li>`).join("") + "</ul>";
        selectedItems = selectedItems.filter(id => !dangling.includes(id));
        showPullDialog = true;
    } else {
        executeAction(DockerArtefactAction.Pull);
    }
}

function executeAction(action: DockerArtefactAction) {
    ctx?.startAction();
    socketStore.emitAgent(endpoint, "executeDockerArtefactAction", artefact.name, action, selectedItems.map(id => dataMap.get(id)?.actionIds[action] ?? id), (res: { ok: boolean; msg?: string }) => {
        ctx?.stopAction();
        socketStore.toastRes(res as any);
        loadData();
    });
}

onMount(loadData);
</script>

<div class="artefact-wrap">
    <!-- Action buttons -->
    <div class="btn-group mb-3 action-bar">
        {#if artefact.actions.includes(DockerArtefactAction.Prune)}
            <button class="btn btn-primary me-1" disabled={ctx?.processing} onclick={() => (showPruneDialog = true)}>
                <Icon name="wrench" /> {$t("prune")}
            </button>
        {/if}
        {#if artefact.actions.includes(DockerArtefactAction.Pull)}
            <button class="btn btn-normal me-1" disabled={ctx?.processing || selectedItems.length === 0} onclick={checkOpenPullDialog}>
                <Icon name="cloud-arrow-down" /> {$t("pull")}
            </button>
        {/if}
        {#if artefact.actions.includes(DockerArtefactAction.Remove)}
            <button class="btn btn-danger" disabled={ctx?.processing || selectedItems.length === 0} onclick={() => (showDeleteDialog = true)}>
                <Icon name="trash" /> {$t("delete")}
            </button>
        {/if}
    </div>

    {#if fetchingData}
        <div class="loading">{$t("fetchingData")}</div>
    {:else}
        <div class="table-responsive">
            <table class="table table-sm table-striped">
                <thead>
                    <tr>
                        <th></th>
                        {#each dataHeader as title}
                            <th class="sortable" onclick={() => toggleSort(title)}>
                                {title}
                                <span class="sort-sym">{sortCol === title ? (sortDir === "UP" ? "▲" : "▼") : ""}</span>
                            </th>
                        {/each}
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {#each tableData as item (item.id)}
                        <tr>
                            <td>
                                <input
                                    type="checkbox"
                                    class="form-check-input row-check"
                                    checked={selectedItems.includes(item.id)}
                                    onchange={(e) => {
                                        if ((e.target as HTMLInputElement).checked) {
                                            selectedItems = [...selectedItems, item.id];
                                        } else {
                                            selectedItems = selectedItems.filter(i => i !== item.id);
                                        }
                                    }}
                                />
                            </td>
                            {#each Object.values(item.values) as value}
                                <td class="artefact-cell">{getValue(value)}</td>
                            {/each}
                            <td class="action-cell text-nowrap">
                                {#if item.dangling}
                                    <span class="badge bg-info me-2">{item.danglingLabel}</span>
                                {/if}
                                {#if artefact.name === "network"}
                                    <button class="btn btn-sm btn-outline-secondary py-0 px-1" title={$t("networkInspect")} onclick={() => openNetworkInspect(item.id)}>
                                        <Icon name="circle-info" />
                                    </button>
                                {/if}
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}
</div>

<!-- Prune dialog -->
<Confirm
    bind:open={showPruneDialog}
    title="{$t('prune')} {$tn(artefact.name, 2)}"
    yesText={$t("prune")}
    btnStyle="btn-danger"
    onyes={() => executeAction(pruneAll ? DockerArtefactAction.PruneAll : DockerArtefactAction.Prune)}
    onno={() => (pruneAll = false)}
>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    <p>{@html $t(artefact.name + "PruneMsg")}</p>
    {#if artefact.actions.includes(DockerArtefactAction.PruneAll)}
        <div class="form-check form-switch">
            <input id="prune-all-{artefact.name}" class="form-check-input" type="checkbox" bind:checked={pruneAll} />
            <label class="form-check-label" for="prune-all-{artefact.name}">{$t(artefact.name + "PruneAll")}</label>
        </div>
    {/if}
</Confirm>

<!-- Pull dialog -->
<Confirm
    bind:open={showPullDialog}
    title="{$t('pull')} {$tn(artefact.name, 2)}"
    yesText={$t("pull")}
    btnStyle="btn-primary"
    onyes={() => executeAction(DockerArtefactAction.Pull)}
>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    <p>{@html $t("imagePullInfoMsg")}</p>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    <p>{@html pullDanglingList}</p>
</Confirm>

<!-- Delete dialog -->
<Confirm
    bind:open={showDeleteDialog}
    title="{$t('delete')} {$tn(artefact.name, 2)}"
    yesText={$t("delete")}
    btnStyle="btn-danger"
    onyes={() => executeAction(DockerArtefactAction.Remove)}
>
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    <p>{@html $t(artefact.name + "DeleteMsg")}</p>
</Confirm>

{#if artefact.name === "network"}
    <NetworkInspectModal bind:open={showNetworkInspect} {endpoint} networkId={inspectNetworkId} />
{/if}

<style>
.artefact-wrap { display: flex; flex-direction: column; }

.action-bar { display: flex; flex-wrap: wrap; gap: 4px; }

.loading { padding: 1rem; color: var(--arbour-text-muted); }

.sortable { cursor: pointer; user-select: none; }
.sort-sym { font-family: monospace; margin-left: 4px; color: var(--arbour-primary); }

.artefact-cell {
    max-width: 200px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.row-check { width: 1em; height: 1em; margin: 0; cursor: pointer; }

.py-0 { padding-top: 0; padding-bottom: 0; }
.px-1 { padding-left: 0.25rem; padding-right: 0.25rem; }
</style>
