// frontend/src/components/NetworkInput.vue
<template>
    <div>
        <h5>{{ $t("Internal Networks") }}</h5>
        <ul class="list-group">
            <li v-for="(networkRow, index) in networkList as {name: string, data: any}[]" :key="index" class="list-group-item">
                <input v-model="networkRow.name" type="text" class="no-bg domain-input" :placeholder="$t(`Network name...`)" />
                <font-awesome-icon icon="times" class="action remove ms-2 me-3 text-danger" @click="remove(index)" />
            </li>
        </ul>

        <button class="btn btn-normal btn-sm mt-3 me-2" @click="addField">{{ $t("addInternalNetwork") }}</button>

        <h5 class="mt-3">{{ $t("External Networks") }}</h5>

        <div v-if="externalNetworkList.length === 0">
            {{ $t("No External Networks") }}
        </div>

        <div v-for="(networkName, index) in externalNetworkList" :key="networkName" class="form-check form-switch my-3">
            <input :id=" 'external-network' + index" v-model="selectedExternalList[networkName]" class="form-check-input" type="checkbox">

            <label class="form-check-label" :for=" 'external-network' +index">
                {{ networkName }}
            </label>

            <span v-if="false" class="text-danger ms-2 delete">Delete</span>
        </div>

        <!--div v-if="false" class="input-group mb-3">
            <input
                placeholder="New external network name..."
                class="form-control"
                @keyup.enter="createExternelNetwork"
            />
            <button class="btn btn-normal btn-sm  me-2" type="button">
                {{ $t("createExternalNetwork") }}
            </button>
        </div>

        <div v-if="false">
            <button class="btn btn-primary btn-sm mt-3 me-2" @click="applyToComposeDocument">{{ $t("applyToYAML") }}</button>
        </div-->
    </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { ComposeDocument, ComposeNetwork } from "../../../common/compose-document";
import { StackData } from "../../../common/types";
import type { SocketRes } from "../vue-augmentation";

interface ComposePage {
    composeDocument: ComposeDocument;
    stack: StackData;
    editorFocus: boolean;
    endpoint: string;
}

export default defineComponent({

    data() {
        return {
            networkList: [] as { name: string; data: unknown }[],
            externalList: {} as Record<string, Record<string, unknown>>,
            selectedExternalList: {} as Record<string, boolean>,
            externalNetworkList: [] as string[],
        };
    },
    computed: {
        composePage(): ComposePage {
            return this.$parent!.$parent as unknown as ComposePage;
        },

        composeDocument(): ComposeDocument {
            return this.composePage.composeDocument;
        },

        stack(): StackData {
            return this.composePage.stack;
        },

        editorFocus() {
            return this.composePage.editorFocus;
        },

        endpoint() {
            return this.composePage.endpoint;
        },
    },
    watch: {
        "composeDocument.networks.composeData.data": {
            handler() {
                if (this.editorFocus) {
                    console.debug("jsonConfig.networks changed");
                    this.loadNetworkList();
                }
            },
            deep: true,
        },

        selectedExternalList: {
            handler() {
                for (const networkName in this.selectedExternalList) {
                    const enable = this.selectedExternalList[networkName];

                    if (enable) {
                        if (!this.externalList[networkName]) {
                            this.externalList[networkName] = {};
                        }
                        this.externalList[networkName].external = true;
                    } else {
                        delete this.externalList[networkName];
                    }
                }
                this.applyToComposeDocument();
            },
            deep: true,
        },

        networkList: {
            handler() {
                this.applyToComposeDocument();
            },
            deep: true,
        }

    },
    mounted() {
        this.loadNetworkList();
        this.loadExternalNetworkList();
    },
    methods: {
        loadNetworkList() {
            this.networkList = [];
            this.externalList = {};

            for (const [ name, network ] of Object.entries(this.composeDocument.networks.getNetworks()) as [string, ComposeNetwork][]) {
                const networkObj = {
                    name: name,
                    data: network.composeData.data,
                };

                if (network.external) {
                    this.externalList[name] = Object.assign({}, networkObj.data);
                } else {
                    this.networkList.push(networkObj);
                }
            }

            // Restore selectedExternalList
            this.selectedExternalList = {};
            for (const networkName in this.externalList) {
                this.selectedExternalList[networkName] = true;
            }
        },

        loadExternalNetworkList() {
            this.$root.emitAgent(this.endpoint, "getDockerNetworkList", (res: SocketRes) => {
                if (res.ok) {
                    this.externalNetworkList = (res.dockerNetworkList as string[]).filter((n) => {
                        // Filter out this stack networks
                        if (n.startsWith(this.stack.name + "_")) {
                            return false;
                        }
                        // They should be not supported.
                        // https://docs.docker.com/compose/compose-file/06-networks/#host-or-none
                        if (n === "none" || n === "host" || n === "bridge") {
                            return false;
                        }
                        return true;
                    });
                } else {
                    this.$root.toastRes(res);
                }
            });
        },

        addField() {
            this.networkList.push({
                name: "",
                data: {},
            });
        },

        remove(index: number) {
            this.networkList.splice(index, 1);
            this.applyToComposeDocument();
        },

        applyToComposeDocument() {
            if (this.editorFocus) {
                return;
            }

            const networks: Record<string, unknown> = {};

            // Internal networks
            for (const networkRow of this.networkList) {
                networks[networkRow.name] = networkRow.data;
            }

            // External networks
            for (const networkName in this.externalList) {
                networks[networkName] = this.externalList[networkName];
            }

            this.composeDocument.networks.replace(networks);

            console.debug("applyToComposeDocument", networks);
        }

    },
});
</script>

<style lang="scss" scoped>
@import "../styles/vars.scss";

.list-group {
    background-color: var(--arbour-bg-deep);

    li {
        display: flex;
        align-items: center;
        padding: 10px 0 10px 10px;

        .domain-input {
            flex-grow: 1;
            background-color: var(--arbour-bg-deep);
            border: none;
            color: var(--arbour-text);
            outline: none;
        }
    }
}

.delete {
    text-decoration: underline;
    font-size: 13px;
    cursor: pointer;
}
</style>

// frontend/src/lib/components/NetworkInput.svelte
<script lang="ts">
import { getContext, onMount } from "svelte";
import { t } from "svelte-i18n";
import { socketStore } from "$lib/stores/socket.svelte";
import type { SocketRes } from "$lib/types";
import { COMPOSE_CONTEXT, type ComposeContext } from "$lib/context";
import type { ComposeNetwork } from "../../../../common/compose-document";
import Icon from "./Icon.svelte";

const ctx = getContext<ComposeContext>(COMPOSE_CONTEXT);

type NetworkRow = { name: string; data: unknown };

let networkList = $state<NetworkRow[]>([]);
let externalList = $state<Record<string, Record<string, unknown>>>({});
let selectedExternalList = $state<Record<string, boolean>>({});
let externalNetworkList = $state<string[]>([]);

let prevNetworksData: unknown = null;

$effect(() => {
    const networksData = ctx.composeDocument.networks.composeData.data;
    if (ctx.editorFocus && networksData !== prevNetworksData) {
        prevNetworksData = networksData;
        loadNetworkList();
    }
});

$effect(() => {
    void networkList.map(n => n.name); // track mutations
    applyToComposeDocument();
});

$effect(() => {
    const selected = { ...selectedExternalList }; // track
    for (const networkName in selected) {
        const enable = selected[networkName];
        if (enable) {
            if (!externalList[networkName]) {
                externalList[networkName] = {};
            }
            externalList[networkName].external = true;
        } else {
            const next = { ...externalList };
            delete next[networkName];
            externalList = next;
        }
    }
    applyToComposeDocument();
});

function loadNetworkList() {
    const rows: NetworkRow[] = [];
    const ext: Record<string, Record<string, unknown>> = {};

    for (const [ name, network ] of Object.entries(ctx.composeDocument.networks.getNetworks()) as [string, ComposeNetwork][]) {
        if (network.external) {
            ext[name] = Object.assign({}, network.composeData.data as Record<string, unknown>);
        } else {
            rows.push({ name,
                data: network.composeData.data });
        }
    }

    networkList = rows;
    externalList = ext;

    const sel: Record<string, boolean> = {};
    for (const name in ext) {
        sel[name] = true;
    }
    selectedExternalList = sel;
}

function loadExternalNetworkList() {
    socketStore.emitAgent(ctx.endpoint, "getDockerNetworkList", (res: SocketRes & { dockerNetworkList?: string[] }) => {
        if (res.ok) {
            externalNetworkList = (res.dockerNetworkList ?? []).filter(n => {
                if (n.startsWith(ctx.stack.name + "_")) {
                    return false;
                }
                if (n === "none" || n === "host" || n === "bridge") {
                    return false;
                }
                return true;
            });
        } else {
            socketStore.toastRes(res);
        }
    });
}

function addField() {
    networkList = [ ...networkList, { name: "",
        data: {} }];
}

function remove(index: number) {
    networkList = networkList.filter((_, i) => i !== index);
}

function applyToComposeDocument() {
    if (ctx.editorFocus) {
        return;
    }

    const networks: Record<string, unknown> = {};
    for (const row of networkList) {
        networks[row.name] = row.data;
    }
    for (const name in externalList) {
        networks[name] = externalList[name];
    }
    ctx.composeDocument.networks.replace(networks);
}

onMount(() => {
    loadNetworkList();
    loadExternalNetworkList();
});
</script>

<div class="network-input">
    <h5>{$t("Internal Networks")}</h5>

    {#if networkList.length > 0}
        <ul class="list-group mb-2">
            {#each networkList as row, i (i)}
                <li class="list-group-item network-item">
                    <input
                        type="text"
                        class="form-control no-bg network-name-input"
                        bind:value={row.name}
                        placeholder={$t("Network name...")}
                    />
                    <button class="btn btn-sm btn-hover-danger remove-btn" onclick={() => remove(i)}>
                        <Icon name="xmark" />
                    </button>
                </li>
            {/each}
        </ul>
    {/if}

    <button class="btn btn-sm btn-normal" onclick={addField}>
        {$t("addInternalNetwork")}
    </button>

    <h5 class="mt-3">{$t("External Networks")}</h5>

    {#if externalNetworkList.length === 0}
        <p class="text-muted">{$t("No External Networks")}</p>
    {:else}
        <div class="external-list">
            {#each externalNetworkList as networkName, i (networkName)}
                <div class="form-check form-switch">
                    <input
                        id="ext-net-{i}"
                        class="form-check-input"
                        type="checkbox"
                        checked={selectedExternalList[networkName] ?? false}
                        onchange={(e) => {
                            selectedExternalList = {
                                ...selectedExternalList,
                                [networkName]: (e.target as HTMLInputElement).checked
                            };
                        }}
                    />
                    <label class="form-check-label" for="ext-net-{i}">{networkName}</label>
                </div>
            {/each}
        </div>
    {/if}
</div>

<style>
.network-input { display: flex; flex-direction: column; }

h5 { margin: 0 0 0.5rem; font-size: 0.9rem; font-weight: 600; }

.network-item {
    display: flex;
    align-items: center;
    padding: 0.4rem 0.5rem 0.4rem 0.75rem;
}

.network-name-input {
    flex: 1;
    background: none;
    border: none;
    padding: 0;
    color: var(--arbour-text);
    outline: none;
    font-size: 0.9rem;
    min-width: 0;
}

.remove-btn { flex-shrink: 0; }

.external-list { display: flex; flex-direction: column; }
</style>
