// frontend/src/components/Terminal.vue
<template>
    <div class="shadow-box">
        <div v-pre ref="terminal" class="main-terminal"></div>
    </div>
</template>

<script>
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { TERMINAL_COLS, TERMINAL_ROWS } from "../../../common/util-common";

function makeTimestampTransform(mode) {
    if (mode === "full") {
        return null;
    }
    // Regex literals with /g are stateful; create fresh ones per call via factory
    const iso = () => /\d{4}-\d{2}-\d{2}T(\d{2}:\d{2}:\d{2})(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?/g;
    const apache = () => /\[\d{2}\/\w+\/\d{4}:(\d{2}:\d{2}:\d{2}) [+-]\d{4}\]/g;
    const spaceDate = () => /\d{4}[-/]\d{2}[-/]\d{2} (\d{2}:\d{2}:\d{2})(?:\.\d+)?/g;
    if (mode === "none") {
        return (data) => data.replace(iso(), "").replace(apache(), "").replace(spaceDate(), "");
    }
    // "short" — keep only HH:MM:SS
    return (data) => data
        .replace(iso(), (_, t) => t)
        .replace(apache(), (_, t) => t)
        .replace(spaceDate(), (_, t) => t);
}

export default {
    /**
     * @type {Terminal}
     */
    terminal: null,
    components: {

    },
    props: {
        name: {
            type: String,
            required: true,
        },

        endpoint: {
            type: String,
            required: true,
        },

        // Require if mode is interactive
        stackName: {
            type: String,
            default: undefined,
        },

        // Require if mode is interactive
        serviceName: {
            type: String,
            default: undefined,
        },

        // Require if mode is interactive
        shell: {
            type: String,
            default: "bash",
        },

        rows: {
            type: Number,
            default: TERMINAL_ROWS,
        },

        cols: {
            type: Number,
            default: TERMINAL_COLS,
        },

        // Mode
        // displayOnly: Only display terminal output
        // mainTerminal: Allow input limited commands and output
        // interactive: Free input and output
        mode: {
            type: String,
            default: "displayOnly",
        },

        // "full" = show all timestamps, "short" = HH:MM:SS only, "none" = strip timestamps
        timestampMode: {
            type: String,
            default: "full",
        },
    },
    emits: [ "has-data" ],
    data() {
        return {
            terminalInputBuffer: "",
            cursorPosition: 0,
        };
    },
    watch: {
        timestampMode(mode) {
            this.$root.setTerminalTransform(this.name, makeTimestampTransform(mode));
            this.clearTerminal();
            this.bind();
        },
    },
    created() {

    },
    mounted() {
        console.debug("Terminal " + this.name + " mounted");

        let cursorBlink = true;

        if (this.mode === "displayOnly") {
            cursorBlink = false;
        }

        this.terminal = new Terminal({
            fontSize: 14,
            fontFamily: "'JetBrains Mono', monospace",
            cursorBlink,
            cols: this.cols,
            rows: this.rows,
        });

        if (this.mode === "mainTerminal") {
            this.mainTerminalConfig();
        } else if (this.mode === "interactive") {
            this.interactiveTerminalConfig();
        }

        //this.terminal.loadAddon(new WebLinksAddon());

        // Bind to a div
        this.terminal.open(this.$refs.terminal);

        if (this.mode !== "displayOnly") {
            this.terminal.focus();
        }

        // Notify parent component when data is received
        this.terminal.onCursorMove(() => {
            console.debug("onData triggered");
            this.$emit("has-data");
        });

        this.$root.setTerminalTransform(this.name, makeTimestampTransform(this.timestampMode));
        this.bind();

        // Create a new Terminal
        if (this.mode === "mainTerminal") {
            this.$root.emitAgent(this.endpoint, "mainTerminal", this.name, (res) => {
                if (!res.ok) {
                    this.$root.toastRes(res);
                }
            });
        }
        // Fit the terminal width to the div container size after terminal is created.
        this.updateTerminalSize();
    },

    unmounted() {
        console.debug("Terminal " + this.name + " unmounted");

        window.removeEventListener("resize", this.onResizeEvent); // Remove the resize event listener from the window object.
        this.$root.unbindTerminal(this.endpoint, this.name);
        this.$root.setTerminalTransform(this.name, null);
        this.terminal.dispose();
    },

    methods: {
        rebind() {
            this.$root.setTerminalTransform(this.name, makeTimestampTransform(this.timestampMode));
            this.clearTerminal();
            this.bind();
        },

        bind(endpoint, name) {
            // Workaround: normally this.name should be set, but it is not sometimes, so we use the parameter, but eventually this.name and name must be the same name
            if (name) {
                //this.$root.unbindTerminal(endpoint, name);
                this.$root.bindTerminal(endpoint, name, this.terminal);
                console.debug("Terminal bound via parameter: " + name);
            } else if (this.name) {
                //this.$root.unbindTerminal(this.endpoint, this.name);
                this.$root.bindTerminal(this.endpoint, this.name, this.terminal);
                console.debug("Terminal bound: " + this.name);
            } else {
                console.debug("Terminal name not set");
            }
        },

        clearTerminal() {
            this.terminal.clear();
            this.terminalInputBuffer = "";
            this.cursorPosition = 0;
        },

        removeInput() {
            const backspaceCount = this.terminalInputBuffer.length;
            const backspaces = "\b \b".repeat(backspaceCount);
            this.cursorPosition = 0;
            this.terminal.write(backspaces);
            this.terminalInputBuffer = "";
        },

        mainTerminalConfig() {
            this.terminal.onKey(e => {
                const code = e.key.charCodeAt(0);
                console.debug("Encode: " + JSON.stringify(e.key));

                if (e.key === "\r") {
                    // Return if no input
                    if (this.terminalInputBuffer.length === 0) {
                        return;
                    }

                    const buffer = this.terminalInputBuffer;

                    // Remove the input from the terminal
                    this.removeInput();

                    this.$root.emitAgent(this.endpoint, "terminalInput", this.name, buffer + e.key, (err) => {
                        this.$root.toastError(err.msg);
                    });

                } else if (code === 127) { // Backspace
                    if (this.cursorPosition > 0) {
                        this.terminal.write("\b \b");
                        this.cursorPosition--;
                        this.terminalInputBuffer = this.terminalInputBuffer.slice(0, -1);
                    }
                } else if (e.key === "\u001B\u005B\u0041" || e.key === "\u001B\u005B\u0042") {      // UP OR DOWN
                    // Do nothing

                } else if (e.key === "\u001B\u005B\u0043") {      // RIGHT
                    // TODO
                } else if (e.key === "\u001B\u005B\u0044") {      // LEFT
                    // TODO
                } else if (e.key === "\u0003") {      // Ctrl + C
                    console.debug("Ctrl + C");
                    this.$root.emitAgent(this.endpoint, "terminalInput", this.name, e.key);
                    this.removeInput();
                } else {
                    this.cursorPosition++;
                    this.terminalInputBuffer += e.key;
                    this.terminal.write(e.key);
                }
            });
        },

        interactiveTerminalConfig() {
            this.terminal.onKey(e => {
                this.$root.emitAgent(this.endpoint, "terminalInput", this.name, e.key, (res) => {
                    if (!res.ok) {
                        this.$root.toastRes(res);
                    }
                });
            });
        },

        /**
         * Update the terminal size to fit the container size.
         *
         * If the terminalFitAddOn is not created, creates it, loads it and then fits the terminal to the appropriate size.
         * It then addes an event listener to the window object to listen for resize events and calls the fit method of the terminalFitAddOn.
         */
        updateTerminalSize() {
            if (!Object.hasOwn(this, "terminalFitAddOn")) {
                this.terminalFitAddOn = new FitAddon();
                this.terminal.loadAddon(this.terminalFitAddOn);
                window.addEventListener("resize", this.onResizeEvent);
            }
            this.terminalFitAddOn.fit();
        },
        /**
         * Handles the resize event of the terminal component.
         */
        onResizeEvent() {
            this.terminalFitAddOn.fit();
            let rows = this.terminal.rows;
            let cols = this.terminal.cols;
            this.$root.emitAgent(this.endpoint, "terminalResize", this.name, rows, cols);
        }
    }
};
</script>

<style scoped lang="scss">
.main-terminal {
    height: 100%;
}
</style>

<style lang="scss">
.terminal {
    background-color: black !important;
    height: 100%;
}
</style>

// frontend/src/lib/components/Terminal.svelte
<script lang="ts">
import { onMount, onDestroy } from "svelte";
import { Terminal as XTerm } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { socketStore } from "$lib/stores/socket.svelte";
import { TERMINAL_COLS, TERMINAL_ROWS } from "../../../../common/util-common";

const {
    name,
    endpoint,
    stackName = undefined,
    serviceName = undefined,
    shell = "bash",
    rows = TERMINAL_ROWS,
    cols = TERMINAL_COLS,
    mode = "displayOnly",
    timestampMode = "full",
    onhasdata = undefined,
} = $props<{
    name: string;
    endpoint: string;
    stackName?: string;
    serviceName?: string;
    shell?: string;
    rows?: number;
    cols?: number;
    mode?: "displayOnly" | "mainTerminal" | "interactive";
    timestampMode?: "full" | "short" | "none";
    onhasdata?: () => void;
}>();

let terminalEl: HTMLDivElement;
let terminal: XTerm;
let fitAddon: FitAddon;
let terminalInputBuffer = "";
let cursorPosition = 0;
let mounted = false; // plain (non-reactive) flag, won't re-trigger $effect

function makeTimestampTransform(m: string): ((data: string) => string) | null {
    if (m === "full") return null;
    const iso = () => /\d{4}-\d{2}-\d{2}T(\d{2}:\d{2}:\d{2})(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})?/g;
    const apache = () => /\[\d{2}\/\w+\/\d{4}:(\d{2}:\d{2}:\d{2}) [+-]\d{4}\]/g;
    const spaceDate = () => /\d{4}[-/]\d{2}[-/]\d{2} (\d{2}:\d{2}:\d{2})(?:\.\d+)?/g;
    if (m === "none") {
        return (data) => data.replace(iso(), "").replace(apache(), "").replace(spaceDate(), "");
    }
    return (data) => data
        .replace(iso(), (_, t: string) => t)
        .replace(apache(), (_, t: string) => t)
        .replace(spaceDate(), (_, t: string) => t);
}

function clearTerminal() {
    terminal.clear();
    terminalInputBuffer = "";
    cursorPosition = 0;
}

function removeInput() {
    const backspaceCount = terminalInputBuffer.length;
    terminal.write("\b \b".repeat(backspaceCount));
    cursorPosition = 0;
    terminalInputBuffer = "";
}

function bind(ep?: string, n?: string) {
    const resolvedEndpoint = ep ?? endpoint;
    const resolvedName = n ?? name;
    if (resolvedName) {
        socketStore.bindTerminal(resolvedEndpoint, resolvedName, terminal);
    }
}

function rebind() {
    socketStore.setTerminalTransform(name, makeTimestampTransform(timestampMode));
    clearTerminal();
    bind();
}

function updateTerminalSize() {
    if (!fitAddon) {
        fitAddon = new FitAddon();
        terminal.loadAddon(fitAddon);
        window.addEventListener("resize", onResizeEvent);
    }
    fitAddon.fit();
}

function onResizeEvent() {
    fitAddon.fit();
    socketStore.emitAgent(endpoint, "terminalResize", name, terminal.rows, terminal.cols);
}

function mainTerminalConfig() {
    terminal.onKey((e) => {
        const code = e.key.charCodeAt(0);

        if (e.key === "\r") {
            if (terminalInputBuffer.length === 0) return;
            const buffer = terminalInputBuffer;
            removeInput();
            socketStore.emitAgent(endpoint, "terminalInput", name, buffer + e.key, (err: { msg: string }) => {
                socketStore.toastError(err.msg);
            });
        } else if (code === 127) {
            if (cursorPosition > 0) {
                terminal.write("\b \b");
                cursorPosition--;
                terminalInputBuffer = terminalInputBuffer.slice(0, -1);
            }
        } else if (e.key === "[A" || e.key === "[B") {
            // UP/DOWN — no-op
        } else if (e.key === "") {
            socketStore.emitAgent(endpoint, "terminalInput", name, e.key);
            removeInput();
        } else {
            cursorPosition++;
            terminalInputBuffer += e.key;
            terminal.write(e.key);
        }
    });
}

function interactiveTerminalConfig() {
    terminal.onKey((e) => {
        socketStore.emitAgent(endpoint, "terminalInput", name, e.key, (res: { ok: boolean; msg: string }) => {
            if (!res.ok) socketStore.toastError(res.msg);
        });
    });
}

$effect(() => {
    const mode_ = timestampMode; // track reactively
    if (!mounted) return;        // skip initial run — onMount handles setup
    socketStore.setTerminalTransform(name, makeTimestampTransform(mode_));
    clearTerminal();
    bind();
});

onMount(() => {
    terminal = new XTerm({
        fontSize: 14,
        fontFamily: "'JetBrains Mono', monospace",
        cursorBlink: mode !== "displayOnly",
        cols,
        rows,
    });

    if (mode === "mainTerminal") mainTerminalConfig();
    else if (mode === "interactive") interactiveTerminalConfig();

    terminal.open(terminalEl);

    if (mode !== "displayOnly") terminal.focus();

    terminal.onCursorMove(() => onhasdata?.());

    socketStore.setTerminalTransform(name, makeTimestampTransform(timestampMode));
    bind();

    mounted = true;

    if (mode === "mainTerminal") {
        socketStore.emitAgent(endpoint, "mainTerminal", name, (res: { ok: boolean }) => {
            if (!res.ok) socketStore.toastRes(res as any);
        });
    }

    updateTerminalSize();
});

onDestroy(() => {
    window.removeEventListener("resize", onResizeEvent);
    socketStore.unbindTerminal(endpoint, name);
    socketStore.setTerminalTransform(name, null);
    terminal?.dispose();
});

export { clearTerminal, bind, rebind, updateTerminalSize };
</script>

<div class="terminal-wrap">
    <div bind:this={terminalEl} class="main-terminal"></div>
</div>

<style>
.terminal-wrap {
    background-color: #000;
    border-radius: var(--arbour-radius);
    overflow: hidden;
    height: 100%;
}

.main-terminal {
    height: 100%;
}

:global(.terminal-wrap .xterm) {
    height: 100%;
}
</style>
