// frontend/src/components/settings/About.vue
<template>
    <div class="d-flex justify-content-center align-items-center">
        <div class="logo d-flex flex-column justify-content-center align-items-center">
            <AppLogo class="my-4" :size="200" />
            <div class="fs-4 fw-bold">Arbour</div>
            <div>{{ $t("Version") }}: {{ $root.info.version }}</div>
            <div class="frontend-version">{{ $t("Frontend Version") }}: {{ $root.frontendVersion }}</div>

            <div v-if="!$root.isFrontendBackendVersionMatched" class="alert alert-warning mt-4" role="alert">
                ⚠️ {{ $t("Frontend Version do not match backend version!") }}
            </div>

            <div class="my-3 update-link"><a href="https://github.com/turtleful/arbour/releases" target="_blank" rel="noopener">{{ $t("Check Update On GitHub") }}</a></div>

            <div class="mt-1">
                <div class="form-check">
                    <label><input v-model="settings.checkUpdate" type="checkbox" @change="saveSettings()" /> {{ $t("Show update if available") }}</label>
                </div>

                <div class="form-check">
                    <label><input v-model="settings.checkBeta" type="checkbox" :disabled="!settings.checkUpdate" @change="saveSettings()" /> {{ $t("Also check beta release") }}</label>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import AppLogo from "../AppLogo.vue";

export default {
    components: {
        AppLogo,
    },

    computed: {
        settings() {
            return this.$parent.$parent.$parent.settings;
        },
        saveSettings() {
            return this.$parent.$parent.$parent.saveSettings;
        },
        settingsLoaded() {
            return this.$parent.$parent.$parent.settingsLoaded;
        },
    },

    watch: {

    }
};
</script>

<style lang="scss" scoped>
.logo {
    margin: 4em 1em;
}

.update-link {
    font-size: 0.8em;
}

.frontend-version {
    font-size: 0.9em;
    color: var(--arbour-text-muted);
}

</style>

// frontend/src/lib/components/settings/About.svelte
<script lang="ts">
import { t } from "svelte-i18n";
import { socketStore } from "$lib/stores/socket.svelte";
import { settingsStore } from "$lib/stores/settings.svelte";
import AppLogo from "$lib/components/AppLogo.svelte";
</script>

<div class="text-center my-4">
    <AppLogo size={160} />
    <div class="app-name mt-2">Arbour</div>
    <div class="version-line">{$t("Version")}: {socketStore.info.version as string ?? "—"}</div>
    <div class="text-muted">{$t("Frontend Version")}: {FRONTEND_VERSION}</div>

    {#if !socketStore.isFrontendBackendVersionMatched}
        <div class="alert alert-warning mt-3" role="alert">
            ⚠️ {$t("Frontend Version do not match backend version!")}
        </div>
    {/if}

    <div class="mt-3">
        <a
            href="https://github.com/turtleful/arbour/releases"
            target="_blank"
            rel="noopener noreferrer"
        >
            {$t("Check Update On GitHub")}
        </a>
    </div>

    <div class="mt-4 text-start mx-auto" style="max-width: 360px;">
        <div class="form-check form-switch">
            <input
                id="check-update"
                class="form-check-input"
                type="checkbox"
                bind:checked={settingsStore.settings.checkUpdate}
                onchange={() => settingsStore.save()}
            />
            <label class="form-check-label" for="check-update">{$t("Show update if available")}</label>
        </div>
        <div class="form-check form-switch">
            <input
                id="check-beta"
                class="form-check-input"
                type="checkbox"
                bind:checked={settingsStore.settings.checkBeta}
                disabled={!settingsStore.settings.checkUpdate}
                onchange={() => settingsStore.save()}
            />
            <label class="form-check-label" for="check-beta">{$t("Also check beta release")}</label>
        </div>
    </div>
</div>

<style>
.app-name { font-size: 1.5rem; font-weight: bold; }
.version-line { font-size: 0.95rem; }
</style>
